### ISSUE TITLE
update and fix capture + fix capture~ 'bug'

### ISSUE THREAD

**Issue by porres** [porres/pd-cyclone#116]
capture needs to have a new @precision attribute, which sets how many decimal points it can display. On this comment I describe the capture deal, on the next one I'll talk about capture~

This needs some thought, as things are different in the pd world. In Pd we can have exponential float format, that doesn't seem to be the case with max. Max seems to have a maximum of 6 decimal point precision, and the display is rounded to that much. 

so 0.00000000001 just becomes 0., while in pd it becomes 1e-11

Now say you put a precision of 3 places in capture and send it a value such as 3.77777, that number is actually stored, but what you can visualize in its window is "3.778"

so it affects the display, not the data, and it rounds it for viewing purposes.

so this is what is needed to be done, but I'm not sure how it will handle exponential floats...

the way things are now it stores and displays exponential float format, I guess we should round it to 6 decimal places!!! Then it makes sense to also implement the @precision attribute!

---

max has an int type and capture stores it as an int, but pd has no int, so how max deals with integer floats?

so, 100000000 with a precision of 3 decimal places becomes

100000000.000

so max doesnt convert it to exponential like 1e+08 and keeps the 3 decimal places

But this is what's happening to pd, it's becoming 1e+08! 

3.0 also becomes 3.000 in max, but in Pd is just "3"

Could we do something about this?

I consider it a bug!

**Comment by porres** [comment]
so... capture~ it's the same issue...

but capture~ has a decimal precision of 4 by default, and you can change this with the 3rd argument.

So what happens is that it treats it as the breaking point for exponential display. So when it has a precision a precision of 4, an integer like 1024 becomes "1.024e+04" which is BAAAAAD

but at least 3.77777 becomes 3.778, that's fine and good

All signals are interpreted as floats, so "3" becomes "3.0000"

In Pd is just "3"

---------------------

So we basically need to fix this issues for both capture and capture~  and then add the precision attribute for capture (which is already in capture~ as an argument).

**Comment by porres** [comment]
finally, there's also a new 2nd outlet for capture:

-  The captured contents are sent out the left outlet, one at a time, in response to the dump message.

**Comment by LGoodacre** [comment]
[capture] doesn't seem to be working correctly for me (either that or I'm misunderstanding what it does). In the first example in the help file, if I scroll the number from 0 to 8, I get "6 6 6 7 7 7 7 8" It's supposed too be "1 2 3 4 5 6 7 8", right?

Also, the second example inside [pd examples] has a message "one 2 three 4 five 6" going into it. This generates an error message for me. If I put a "list" in front, there is not error message, but then I get only "2 4 6" inside.

**Comment by porres** [comment]
Yeah, there is something pretty screwed up here :) thanks!

**Comment by porres** [comment]
And the weird thing is that it seems to work in cyclone 0.2beta and I we didn't really touch this code yet!!!

**Comment by porres** [comment]
try printing the output from float, you may realize that's what's coming out of the number box anyway. Maybe I'll use a [change] object in the help file to avoid that

**Comment by porres** [comment]
and yeah, we still need to make it accept "anything" and not just list messages!
