### ISSUE TITLE
7 remaining objects for updates

### ISSUE THREAD

**Issue by porres** [porres/pd-cyclone#117]
Besides the 47 completely updated objects,  for a total of 54, we still have this to go:

1) [mousefilter]: (doesn't have attributes): needs to accept and output/filter any message, whatver comes in should come out, like a bang, a list with no list selector, a symbol atom (message with no symbol selector). We did the same thing for other objects

2) [capture]: add attribute

3) [zl]: add attribute and modes

4) [table]: add attributes and methods - there are lots of attributes, maybe a properties window in this case?

signal:

5) [delay~]: signal input, ramp method (partially updated to include maxsize)

6) [play~] attributes and methods

7) [average~]: signal outlet

--------------------------

extra

- [comment]: this has attributes, though I guess we won't actually do this one, cause it's kinda insane to upgrade it from max 4, so lets basically count it out. But it'd be good to add a properties window!

**Comment by porres** [comment]
other remaining objects:

control (4):
- capture
- zl
- table
- comment (though I guess we won't actually do this one, cause it's kinda insane to upgrade it from max 4)

audio (3):
- delay~
- average~
- play~

so plus the above, we got about a dozen to go! 11 to be realistic. The 5 above are really easy in my opinion, so we can quickly get down to about half a dozen to go! This is pretty good for an alpha release :)

**Comment by derekxkwan** [comment]
it looks like spray already handles lists (in addition to pairs)? it's easy work getting rid of the loud dependency though...

**Comment by porres** [comment]
it handles lists but not the list mode, where lists are output in the outlets
