### ISSUE TITLE
annoying errors with buffer classes

### ISSUE THREAD

**Issue by porres** [porres/pd-cyclone#129]
hi, i'm getting an annoying print error with buffir~ poke~ and index~ 

these use the new cybuf dependency.

so, if I have an array that was created after the object, and the object refers to that array name as its argument, and then I save the patch and reopen, a print error will show up saying it didn't find the array... but things still work, it still actually finds the array...

the error is: no such array 'arrayname'

I don't get this kind of error with play~ for instance... but play~ will still complain if i create it with an argument refering to an inexisting array, or when I delete the array

I like play~, it prints the error in a way it should (well, this changed! see below)

Moving on, we still have peek~ wave~ and record~

peek~ won't print any error at all (well, this changed! see below)

wave~ has the same issue I pointed with buffir~ / poke~ and index~ but will also print a 2nd error "arrayname: no such table"

record~ prints only 'not such table' error, and an annoying error when not specifying any array, unlike the rest

and how are things in Max? No error for non existing buffer/array... just that...

I like that you can print an error, don't mind that - even "inconsistent" to max, might be a good idea to keep it, but it's bad if it prints errors when things are actually working... so lets try to make them all work like play~ (well, like play~ used to be, as it changed, see below)

thanks

-----------------

apparently things are changing after changing dependencies....

now play~ is the one which doesn't print any errors and work in a desirable way

and peek~ now prints errors like the rest

record~ will print 2 errors when the table is put in the patch afterwards:  no such array 'x' & x: no such table - AND IT SIMPLY WONT WORK THEN... (fixed in the last pr?)

and also it'll also complain about not finding multiple arrays in the help file

**Comment by derekxkwan** [comment]
**play~:** attributes: interptime f(crossfade for loop interp 50 ms), loop f, loopinterp f (interp around endpoints)

methods:
start (start time) (end-time) (dur): both in ms (end > start = reverse), dur is opt, in ms tells how long to take from start to end (default, normal playback speed?)

pause: self-explanatory, negated with resume

stop: self-explanatory

int 0/1: stop/start (so need a separate float method for main inlet)

**Comment by derekxkwan** [comment]
crossfading between what and what?

**Comment by porres** [comment]
yes, we need a separate float method for the main inlet, I had already created that one, let me check about the crossfade

**Comment by porres** [comment]
so, when you enable "interpolation around the start and end points for a loop" with @loopinterp [int], , you "interpolate" with a "crossfade"...

@loopinterp only happens if you have the loop on - set with the @loop attrinbute

the default crossfad time for @loopinterp is 50ms, but you can change it with @interptime [float]

**Comment by porres** [comment]
but hold on with loopinterp and interptime, i'm yet to better understand it... and max just crashed when i was dealing with it :)

**Comment by porres** [comment]
i'm getting lots of crashes with play! 

Seems this loopinterp  feature is quite fucked up anyway...

all that i hear it does is that it performs a fade in when it restarts playing the file... no actual crossfading.

**Comment by porres** [comment]
GOT IT!!!

if you have a loop section into the file... say it is 5 seconds long, but you loop from 1 sec to 3 seconds...

then, what it does at the loop point, is that it "fades in" starting from 1 second, but it will fade out from 3 seconds and on as long as the interptime, for a maximum of 2 seconds.

**Comment by porres** [comment]
So, not sure what happened, but even now when we still did not get play~ to use the cybuf code, something changed its behaviour. 

I liked the way it was before, where it would complain if i created it with an argument referring to an unexisting array, or when I delete the array, but if the patch was saved with an array that was created later, it wouldn't complain.

I like the way play~ was, it would prints an error only when necessary.

I hope we can make them all behave like that, otherwise it is better to not have any errors.
