### ISSUE TITLE
installation fails for cyclone03prealpha4

### ISSUE THREAD

**Issue by katjav** [porres/pd-cyclone#134]
Compiling cyclone03prealpha4 on Linux succeeds but installing fails because data files are not found on locations defined in the lib makefile:

- Help files are in an apparently renamed directory.
- LICENSE.txt is in a directory called 'maintenance' (not an intuitive title for documentation files).
- Files test.mid and voice.wav seem to be absent, not sure if they are no longer needed?
- Patch cyclone-meta.pd seems to be absent, where is this important file?

Abstraction [number~] isn't included in the datafiles definition.

**Comment by porres** [comment]
yeah, I guess we never tried "installing", sorry for the ignorance, but how do you do it? :)

**Comment by katjav** [comment]
Huh, seriously? Try 'make install objectsdir=./build'. You'll get the errors but after fixing the lib makefile you'll get the installed lib in ./build/cyclone with all the files (and symlinks if needed). You need this for making binary distributions.

**Comment by porres** [comment]
yep, seriously :) please cope with me, haha - I actually cannot believe I was able to pull a lot of this off, I say I'm like a blind man playing soccer, but derek and matt know better than me ;)

**Comment by porres** [comment]
I'll tell you what happened, I see the errors in the end of the process, but everything builds out of the specified ./build/cyclone folder as well as inside the folder, this is weird right? seems like it should only build inside the folder

![screen shot 2016-10-05 at 13 38 34](https://cloud.githubusercontent.com/assets/5360142/19122527/3cac3194-8b01-11e6-8d27-368dc474a611.png)

**Comment by porres** [comment]
anyway, fixing it... no errors no more... 
![screen shot 2016-10-05 at 14 01 37](https://cloud.githubusercontent.com/assets/5360142/19123264/574d200a-8b04-11e6-9b54-c52ec8ff847e.png)

**Comment by porres** [comment]
well, you can try now

https://github.com/porres/pd-cyclone/commit/5ec33210ab576fac3ebf1cb245f33b212167d4c3

**Comment by porres** [comment]
or better yet https://github.com/porres/pd-cyclone/commit/eea402ea4c694e9c2e741cc1791296f0ca2a0b21

**Comment by katjav** [comment]
Installation succeeds now. By the way you can point to any location you like with variable 'objectsdir'. I mentioned 'objectsdir=./build' as an example. In a centralized build system like pd-extended / pd-l2ork it would be the path of the 'extra' directory where all libdirs are installed before packaging.

I wonder, how did you test without installing? Binaries and help patches aren't in the same directory in the source tree so the objects don't load.

**Comment by porres** [comment]
over 7 months I just manually copied help files and binaries to a cyclone folder :)

**Comment by katjav** [comment]
So that is how you created your binary distributions for testing? That's inefficient and hazardous. Anyway now you know how to get it with a simple command. Maybe the best location for installation is outside your source tree, like 'objectsdir=../cyclone-build-tmp'.

By the way I noticed something confusing on my system. An earlier cyclone version was in ~/pd-externals, and when I loaded patch scope~-help.pd from the local cyclone install under test, pd window told me things like 'Scope~: no method for bgcolor'. Meaning pd had preferred ~/pd-externals/cyclone/Scope~ over the local binary. I always thought that it was the other way round, that local objects had priority. But maybe this is only true for abstractions. Can you check how that works on your system? It is crucial info for alpha testers (and of course for all users in the end).

**Comment by porres** [comment]
my system seems to be behaving non deterministically... it can go either way, but it seems to be controllable with abstractions indeed
