### ISSUE TITLE
per-file commit history obscured after renames

### ISSUE THREAD

**Issue by katjav** [porres/pd-cyclone#154]
For a particular class (svf~) I wanted to see commit history to understand what bug(s) were fixed and how, but the only history shown for svf.c was 'drastic reorganising'. The same goes for many other files. This is an unfortunate and inevitable consequence of file renaming. Github is not smart enough to recognize and visualize history across renames.

It would be helpful if you create and upload tags to points in the history just before reorganizations, so we can browse files at those points and have a better chance to see relevant commits per file.

**Comment by porres** [comment]
yeah, drastic reorganising has nothing to do with messing with [svf~], just changing files from a folder to a nother and renaming folder, that is reorganising the structure of all files in the repository.

other than that, the only thing done for [svf~] is making its main inlet not accept floats, which makes sense for a signal filter. This was done for a series of objects and probably updated as one simple commit.

I have to admit I'm really a dummie when it comes to managing github, but at least I have a good personal database of things that were done in cyclone to help people that are curious about it - our changelog is also pretty detailed and can be improved.

**Comment by katjav** [comment]
There have been several changes to svf~. One of these, or the combination of them, have solved a denormals bug. That's great. Now it would be interesting to see the diffs. If we go back to commit 34aa601 and view the history of vcf.c at that point in time, we can at least see four commits where vcf.c was involved. 

I'm not making an issue here of what exactly happened to svf.c, it is just an example. Next time someone wants to see commit history of another file. Imagine a bug was not accidentally fixed, but instead created? So what I'm saying is, if you make special purpose tags to points in history just _before_ file reorganizations, like commit 34aa601, chunks of file history can be accessed through these tags. That is easier than searching through 1000+ commits.
