### ISSUE TITLE
[substitute] and single argument

### ISSUE THREAD

**Issue by LGoodacre** [porres/pd-cyclone#164]
It would be really awesome if [substitute] could be used to filter a term out of a list by taking a single argument, ie.

[1 2 3(
|
[substitute 2]
|
[1 3(

Perhaps it would compromise the compatibility with Max, but you currently need to use quite a collection of objects to perform this task simple in PD, and it would seem to fit nicely into the existing [substitute] syntax.

**Comment by porres** [comment]
it'd break compatibility and the new zl we're working will do that job ;)

**Comment by LGoodacre** [comment]
Ah, can't wait for the new zl!
