### ISSUE TITLE
funbuff

### ISSUE THREAD

**Issue by porres** [porres/pd-cyclone#201]
- the pair of numbers stored and everything must be INTS, cyclone is accepting floats, which is bad!!!
- set message shouldn't clear contents!!! (BUG!!!)
- insert a warning for a copy/cut command without prior select, it should say: "no data to copy"
- a paste command without anything copied should post the error: "clipboard empty" instead of "bad input (no input) -- no data to set"

funbuff is using "loud" for errors, right? could we get rid of that?

I find this one particularly annoying: "funbuff_read: funbuff.txt read successful"

there;s no need for a "funbuff_read", at least for "_read" - lets make it at least just "funbuff"

**Comment by derekxkwan** [comment]
it looks like "set" overwrites? so if there were values for x:1-5, and you're setting for x = 1, you'll end up with 1 element in your funbuff? at least in the code as it is for funbuff_set (which i didn't modify i think), clear is called each time, meaning the old contents are erased. does this mean "paste" should overwrite too? anyways, for undo, it looks like i'll have to be writing a new non-clearing set

**Comment by porres** [comment]
yep, it overwrites in cyclone, but it shouldn't - in Max it doesn't clear, so it only adds!

guess we found a bug ;)

**Comment by derekxkwan** [comment]
there's placeholder code for funbuff_reduce, get rid of it? can't find docu on it

**Comment by porres** [comment]
GET RID!!!

<img width="224" alt="screen shot 2017-01-12 at 00 56 43" src="https://cloud.githubusercontent.com/assets/5360142/21875293/0b5b2542-d862-11e6-898c-1b8069560841.png">

**Comment by porres** [comment]
seems we got rid of warnings, but we should keep and add these:
- insert a warning for a copy/cut command without prior select, it should say: "no data to copy"
- a paste command without anything copied should post the error: "clipboard empty"
