### ISSUE TITLE
peek~ is writing too slow

### ISSUE THREAD

**Issue by porres** [porres/pd-cyclone#205]
in comparison to tabwrite~ using [uzi] and a slider input (i have a patch) 
[peek is slow in drawing.pd.zip](https://github.com/porres/pd-cyclone/files/704764/peek.is.slow.in.drawing.pd.zip)

**Comment by brbrofsvl** [comment]
Are the values slow in displaying, or is it actually not writing as fast?

**Comment by porres** [comment]
yeah, it's just taking too long to display... it writes pretty fast

**Comment by porres** [comment]
that's really evident with the slider + uzi in the example I uploaded

**Comment by porres** [comment]
fixed with PEEK_TICK_TIME
