### ISSUE TITLE
[coll]

### ISSUE THREAD

**Issue by porres** [porres/pd-cyclone#211]

**Comment by porres** [comment]
some extra information about coll

up to alpha 57, it had no threaded option and the 3rd outlet would bang

cyclone 02 uses pd-l2ork's version, that has a threaded number argument in any order and doesn't bang when not in threaded mode.

we fixed and reverted it, by making it bang in the unthreaded mode, and removed the warning saying if it did load or not a file cause it wasn't necessary

**Comment by porres** [comment]
how does coll behave in single threaded CPUs? Raspberry pi, chip and stuff?

**Comment by porres** [comment]
max doesnt break detemrinism and doesnt choke the audio

![screen shot 2017-01-24 at 23 24 32](https://cloud.githubusercontent.com/assets/5360142/22274314/dd7613e6-e28c-11e6-92a3-8eb3bea73d3e.png)

**Comment by derekxkwan** [comment]
- maybe coll_dump isn't threadable, in terms of outlets, it does more than just bang, it spits stuff out of the main outlet. and right now our only callback coll_tick bangs out of the 3rd outlet. maybe something to bring up with the others? 

- so what is filetype supposed to do? it exists in the code, just does nothing.

**Comment by porres** [comment]
dont know about filetype... doesn't seem to be workin in max, reference says:

"Sets the file types which can be read and written into the coll object. The message filetype with no arguments restores the default file behavior."

I guess we could make it work like "filetype" from buffer, which just specifies a filetype for when you write it to a file and give it a name that has no extension...

**Comment by derekxkwan** [comment]
i've done A, haven't pulled it yet. so what should C do? doesn't nosearch only mean it shouldn't look for the file on instantiation, but after words you can definitely tell them to read something and then it should bang. trying to think of how to isolate it so it only bangs the one that received the read message, since how it's set up now, the method doesn't know which particular object is calling it...

**Comment by porres** [comment]
you've done B too, right?

**Comment by porres** [comment]
yeah, about C) if you send it a read message, it should read, maybe that's not a relevant detail, the thing is that, **for unthreadeed mode only**, a read message in one coll seems to affect all colls with the same name...

if the method doesn't know which particular object is calling it... well, this IS WORKING fine for the threaded mode, so just make it the same in unthreaded ;)

**Comment by derekxkwan** [comment]
note to self things to do: [readagain] bang not working, nosearch bangs when it's not supposed to

**Comment by derekxkwan** [comment]
also put back general bangs in collcommon_doread, need for threaded and unthreaded
