### ISSUE TITLE
loadmess: LB_LOAD build errors

### ISSUE THREAD

**Issue by derekxkwan** [porres/pd-cyclone#274]
LB_LOAD, defined in Pure Data's src/g_canvas.h, somehow isn't found by loadmess.c, even though other objects reference this header. FOR NOW, I subbed it out with its defined value of 0, but THIS IS BAD (since LB_LOAD may change in future pd versions) and we do need to find a non-bad solution for this.

**Comment by porres** [comment]
PR #272

**Comment by derekxkwan** [comment]
close?
