### ISSUE TITLE
loadmess: rethink defer 

### ISSUE THREAD

**Issue by derekxkwan** [porres/pd-cyclone#276]
I was talking with @amurtet, who brought up ideas of changing the implementation of defer, who thinks that the implementation should be rethought. It currently relies on a callback (t_clock) that triggers after 10 units (prob ms?)

Here are a few ideas:

1. Make a "global" class like funbuff has for its clipboard, which gets instantiated with the first loadmess object, gets bound by a pointer member of the loadmess struct, and gets freed when the last loadmess gets freed. The point of this would to globally trigger ALL loadmesses. It would handle triggering all defer 0s then all defer 1s. The issue is that this is a bit more complicated to implement than normal and requires a new object class to be instantiated. Plus, not quite sure if this has any advantages over the current callback system (are there issues with the current system? as in due to instantiation order the callback triggers at undesired orders?). It also seems like a waste to do all the work and not have multiple levels of deferredness,.. like defer 0, 1, 2, ,3, 4, 5, etc. and only 2 levels. I know this is for the sake of Max compat.

2. Just set the callback time to 0. This is done with [coll] with the threaded methods as well as the bang when loaded (since we want to bang from an outlet that doesn't exist yet since the new method hasn't returned yet). If there are issues with bang order with lthe callback clock, I don't think this helps the situation.

**Comment by porres** [comment]
this has been hacky in cyclone, apparently, in max, it's kind of a global thing and part of different object's attributes

**Comment by amurtet** [comment]
With the actual design, the main problem is the determinism breaking. You don't know the order of control part and message flow. In Max this is not a problem because they don't have determinism (in a strict Pd sense), so they rely on this priority concept about message ordering. Actually, I don't understand the meaning of defer in Pd apart Max compatibility. The first Derek idea sounds not bad; anyway if you have 2 objs with defer with different priorities (0 = high priority 1 = low priority, just a convention) but in different sub patches what happens? Your global class will be global to the patch.

**Comment by derekxkwan** [comment]
maybe one issue with my global idea: so the first loadmess instantiates a "loadmess_global" that all other loadmesses bind to. how then do we know that all loadmesses are instantiated and bound and then we can start doing the "defer 0" and "defer 1" process? maybe the very last loadmess to get loaded is a "defer 0".

If then our solution is to use a global t_clock associated with "loadmess_global" to wait x samples or whatever then start up the defer process, then we essentially have the same thing as we do now, except more complicated.

**Comment by derekxkwan** [comment]
unless there's some flag or callback in pd that you can query that indicates when an entire patch/savefile is loaded...

**Comment by porres** [comment]
so, this is done
