### ISSUE TITLE
[coll] crahes Pd if used in unthreaded mode (on MsWindows)

### ISSUE THREAD

**Issue by Lucarda** [porres/pd-cyclone#332]
With this behaviour, Pd crashes when opening the help patch.

Tested on Windows 8

**Comment by Lucarda** [comment]
Note that on a clean win10 machine you *can* open the “help-patch” but you can't use [coll], either threaded or not.
This new version uses  “pthreadGC-3.dll” & “libgcc_s_dw2-1.dll”, this last one is not in the PKG so no crashes because it don't load. 
If “libgcc_s_dw2-1.dll” is placed we can use the threaded [coll].

**Comment by porres** [comment]
Hi, I actually have a win10 machine and could not open the help file, Pd crashed!

**Comment by porres** [comment]
Hi, I actually have a win10 machine and could not open the help file, Pd crashed! So, I don't know... there seems to be a conflict here.

I don't understand why we need more .dll dependencies now, wasn't it all fine with the last version (beta1)? We only included pthreadGC-3.dll in the last version and it was fine...

**Comment by Lucarda** [comment]
But you can create a [coll a], right?

**Comment by porres** [comment]
yes, I can create [coll], or [coll a] / whatever...

anyway, you seem to imply libgcc_s_dw2-1.dll is crashing coll, right?

**Comment by porres** [comment]
I'm on Windows 10 Home 64-bit , by the way

**Comment by Lucarda** [comment]
> you seem to imply libgcc_s_dw2-1.dll is crashing coll, right?

I'm not sure about that. But i'm sure that if you create [coll a @threaded 0] you get the crash.

My tests using Dependancywalker results that “libgcc_s_dw2-1.dll” is called by “pthreadGC-3.dll ” which is called by “coll.dll”

**Comment by porres** [comment]
And you do not have any idea why I'm actually getting the crash on windows 10 Home 64 bits, huh? Or is it cause you said that in a "clean" install you don't get a crash, but I might have a "dirty" install... and by dirty, it would mean I also have libgcc_s_dw2-1.dll somewhere?

Anyway, we did include pthreadGC-3.dll in cyclone 0.3 beta 1, just like now, but now you say it also needs libgcc_s_dw2-1.dll, and when you have it, it causes the crash.

How about using Dependancywalker on cyclone 0.3 beta 1? Did it result on “libgcc_s_dw2-1.dll” as well? It seems so, cause you say it is called by "pthreadGC-3.dll"... 

I'm really confused by the need for extra dependencies, it seems that Purr Data, which still has cyclone 0.2, does not need any dependency and works just fine in windows, have you tested it?

**Comment by Lucarda** [comment]
> it would mean I also have libgcc_s_dw2-1.dll somewhere? 

Check your C:\Windows\SysWOW64.
libgcc_s_dw2-1.dll  might have been installed there by some other program.

> I'm really confused by the need for extra dependencies, it seems that Purr Data, which still has cyclone 0.2, does not need any dependency and works just fine in windows, have you tested it 

libgcc_s_dw2-1.dll  is in Purr-Data, in the bin dir.

MsWindows can handle loading dlls if they are:
in the same dir as the caller
in the same dir as the .exe
or in the system folder, “system32” for 32bitOS or “SysWOW64” 32bit-app-on64bitOs

**Comment by porres** [comment]
> Check your C:\Windows\SysWOW64.
> libgcc_s_dw2-1.dll might have been installed there by some other program.

it is... but not pthreadGC-3.dll

> libgcc_s_dw2-1.dll is in Purr-Data, in the bin dir.

I see... cool... but I don't see pthreadGC-3.dll there, how come? And the threaded version of coll works anyway...

**Comment by Lucarda** [comment]
>>Check your C:\Windows\SysWOW64.
libgcc_s_dw2-1.dll might have been installed there by some other program.

>it is... but not pthreadGC-3.dll

but  it is on Cylone

>>libgcc_s_dw2-1.dll is in Purr-Data, in the bin dir.

>I see... cool... but I don't see pthreadGC-3.dll there, how come? And the threaded version of coll works anyway...

Are you sure pthre3 is not on cyclonefolder (of purr-data)?

**Comment by Lucarda** [comment]
Irrc Jonathan is compiling with msys2 which can use “libwinpthread-1.dll” instead of pthre3 that comes with MinGW (msys1.0)
I'm not sure.

**Comment by porres** [comment]
> but it is on Cylone

I know, but it is not the for Purr Data

> Are you sure pthre3 is not on cyclonefolder (of purr-data)?

I am, can you double check? I'm interested to know why it isn't needed in Purr Data

Anyway, it seems we need to ship libgcc_s_dw2-1.dll for cyclone in vanilla in the same way as we do with pthreadGC-3.dll

so how come it was working for you in the last version (cyclone 0.3 beta 1)? Seems you did have libgcc_s_dw2-1.dll in the system folder or elseqhere, right?

**Comment by porres** [comment]
> Irrc Jonathan is compiling with msys2 which can use “libwinpthread-1.dll” instead of pthre3 that comes with MinGW (msys1.0)
> I'm not sure.

I don't see libwinpthread-1.dll in the cyclone folder as well...

I'm using msys 1.0, but for no particular reason, I think you helped me chosing it by the way... anyway, not sure why it is a good thing or not to use it, or if I could use something else (2.0?) for some advantage...

**Comment by porres** [comment]
well, apart from this dependency discussion, which I think is really important, it seems this issue is just something @derekxkwan did

**Comment by porres** [comment]
"Great!
I just checked the w32 pkg with “Dependency Walker” and nothing is missing. Only “pthreadGC-3.dll” is used and it's there."

@Lucarda , this is your message on the cyclone 0.3 beta 1 release, I wonder why the dependency walker did not ask for the libgcc_s_dw2-1.dll  dependency...

**Comment by Lucarda** [comment]
> I am, can you double check? I'm interested to know why it isn't needed in Purr Data 

Check the my post above. “libwinpthread-1.dll ” is in purr-data/bin.

> so how come it was working for you in the last version (cyclone 0.3 beta 1)? Seems you did have libgcc_s_dw2-1.dll in the system folder or elseqhere, right? 

Sure, in my poluted win8.1 which I use normaly. I have other clean machines for this kinds of tests.
libgcc_s_dw2-1.dll is one of many .dlls that are installed on the system folder by Pd-extended installer.
You probably also have pdx installed.
We have to ship dependencies in the deken pkg as if the target machine is totally neutral. 

> this issue is just something @derekxkwan did 

Sure, the bug is just something that has to be checked in the non-!threaded code.

**Comment by porres** [comment]
> Check the my post above. “libwinpthread-1.dll ” is in purr-data/bin.

stupid me, didn't check for that...

Ok, so Purr Data has both dlls in its bin folder. Thanks for clarifying this to me!

**Comment by porres** [comment]
So, I'm also using msys 1.0, why don't I do the same thing as in Purr Data, instead of just copying and pasting pthreadGC-3.dll, right? Should be better...

I'm still curious to ask you why you said Dependency Walker only said “pthreadGC-3.dll” was needed in cyclone 0.3 beta 1 and did not ask for the libgcc_s_dw2-1.dll dependency...

**Comment by Lucarda** [comment]
> , I wonder why the dependency walker did not ask for the libgcc_s_dw2-1.dll dependency... 

We are humans, we are learning & we make mistakes.
That test was a fast one on my poluted machine. (pthread3 not in system folder).
So I  didn't get the error.
Finding deps on a windows machine is an art. It took me a week on 2016 to report all Deken w32 deps. IOhannes updated all zip pkgs. But now they work.

> So, I'm also using msys 1.0, why don't I do the same thing as in Purr Data, instead of just copying and pasting pthreadGC-3.dll, right? Should be better... 

You will end up copying and pasting the dep generated using other compiler.

**Comment by porres** [comment]
fixed

**Comment by porres** [comment]
@Lucarda , can you test building yourself and testing it?

I also made it so that both dlls are copied to the cyclone folder

**Comment by Lucarda** [comment]
Good, its working Ok.

Details:

I used mingw/msys 1:
make pdincludepath=C:/Users/me/Downloads/pd/src pdbinpath=C:/Users/me/Downloads/pd/bin

this only makes the [objects], I had to manually create cyclonefolder with all [objects], helps, stuff & both .dll dep. (i might be missing some command)

My tests with depwalker reveals that both pthread & libgcc are needed by [coll].

Good Work!

**Comment by porres** [comment]
try just "make install objectsdir=../"

**Comment by Lucarda** [comment]
Nice!

I had to use:
make pdincludepath=C:/Users/me/Downloads/pd/src pdbinpath=C:/Users/me/Downloads/pd/bin install objectsdir=C:/cyclone

Because my pd/src & pd/bin are not on the standard location.

Good!
