### ISSUE TITLE
zlclear not working for the zl family

### ISSUE THREAD

**Issue by bennniii** [porres/pd-cyclone#340]
as stated... the word "zlclear" is stored in the object
macOs 10.12.5
Pd 0.47.1

**Comment by porres** [comment]
yeah, we know it, it's on our list ;)

**Comment by porres** [comment]
listed in https://github.com/porres/pd-cyclone/issues/109

**Comment by porres** [comment]
this has been fixed with commit https://github.com/porres/pd-cyclone/commit/7dd6a9ff15e72cfb50763017b37cabdc66b93cfe

stay tuned for the next release!
