### ISSUE TITLE
join conflict

### ISSUE THREAD

**Issue by bennniii** [porres/pd-cyclone#341]
the external "join" seems to to conflict with some abstraction natively included in pd-l2ork v2.2.3

**Comment by porres** [comment]
what do you mean? that there is another external named "join" in purr data? Doesn't seem like a cyclone issue, so I'm closing this.

and by the way, note that cyclone 0.3 is not included in pd-l2ork v2.2.3

**Comment by bennniii** [comment]
you are right, sorry... i created a patch in pd 0.47 using cyclone's [join] object – in pd-l2ork this [join] was replaced with an abstraction that seems to be initially included. my bad

**Comment by porres** [comment]
[cyclone/join] was included in cyclone 0.3, if that wasn't clear

**Comment by bennniii** [comment]
@porres – hope it's ok to ask here: any clue as for *when* cyclone 0.3 will be included in pd-l2ork?

**Comment by porres** [comment]
when 2.2.6 is out
