### ISSUE TITLE
Missing .dll on deken pkg w32 0.3beta2

### ISSUE THREAD

**Issue by Lucarda** [porres/pd-cyclone#344]
"libgcc_s_dw2-1.dll" is not present on he Deken pkg. 0.3beta2-(w32).
This is causing Pd to crash when opening [coll]
Please update the Pkg.

Salutti,
Lucarda.

**Comment by porres** [comment]
hi, did you try compiling the package in the current state?

or do you mean as it is in cyclone beta 2?

If you mean cyclone beta 2, could you try compiling from the source now? Cause I think we already fixed this.

cheers

**Comment by Lucarda** [comment]
Yep, the current state. "libgcc_s_dw2-1.dll" is missing.

**Comment by Lucarda** [comment]
Oops, I migth be wrong. actually putting the .dll crash Pd.
I will try compiling cuz this was fixed as you mention. Anyway [coll] is crashing Pd-0.48-test7

**Comment by porres** [comment]
hi, please be more specific, I'm not following you, I'm confused now. sorry

**Comment by Lucarda** [comment]
Me to but good news. I compiled just know & it works OK.
Did Matt, Derek or You changed the deken pkg?
You are rigth that coll was working last time.
Do you want the binaries?

**Comment by porres** [comment]
well, I'm still confused... 

is "libgcc_s_dw2-1.dll" missing in the current state?

is it missing in the last release (0.3 beta 2?)

> Did Matt, Derek or You changed the deken pkg?

the package wasn't change since its release date

**Comment by Lucarda** [comment]
> is "libgcc_s_dw2-1.dll" missing in the current state?

you can check that. Download it.

**Comment by porres** [comment]
I see the confusion now, by current state, I mean not the downloadable release, I mean the current state now, with many commits ahead the last release. But for that, you'd have to compile and check (I can't compile for windows right now).

My point is that I think this has already been fixed after the release of 0.3 beta 2

**Comment by Lucarda** [comment]
I ment theDeken pkg

**Comment by porres** [comment]
if you compile and check the current state, please let me know. If it is fixed, then we can close this issue

**Comment by Lucarda** [comment]
I have compiled the current state and is working OK.
lets close it but remeber to update the deken pkg.

**Comment by porres** [comment]
we'll update it soon to **cyclone 0.3 beta 3** , but we are still working on further fixes and on including cyclone in purr data

cheers

**Comment by Lucarda** [comment]
Good.
Drop me a line for test before releasing **0.3 beta 3** for w32.
