### ISSUE TITLE
mousestate error: #hammerpoll: couldn't unbind

### ISSUE THREAD

**Issue by porres** [porres/pd-cyclone#351]
I was giving a go at this [rslider], stolen from mmb

[rslider.zip](https://github.com/porres/pd-cyclone/files/1250844/rslider.zip)

and I kept getting this annoying error, funny enough, when opening the help file of mousestate, the error stops happening - I recall something similar happening before, maybe

**Comment by porres** [comment]
by the way, I don't think I'm doing [rslider] for cyclone :) - I was just having fun

**Comment by porres** [comment]
#hammerpoll is only defined at line 439 in shared/hammer/gui.c

**Comment by katjav** [comment]
I'm seeing the same error messages in patches with [mousestate] objects. The issue can be narrowed down to the following observation:
 
If no [mousestate] instance is actually set to 'poll', sending message 'nopoll' to an instance triggers             error `#hammerpoll: couldn't unbind`.

This also explains why opening the helpfile for [mousestate] stops the erratic behavior. In earlier cyclone versions the issue didn't exist, although I don't know in which version exactly it was introduced. From the behavior I guess that there is some global polling object to which [mousestate] (and possibly other objects) can subscribe, and which isn't robustly implemented.

The 'error' itself may be harmless but in that case the error messages are redundant and merely annoying. Some of my older patches use [MouseState] intensively and they spit tons of red lines when used with current cyclone.

**Comment by porres** [comment]
thanks katjav, with your narrowing down, this was easy to fix, sorry it took so long :)
