### ISSUE TITLE
test new loadmess version

### ISSUE THREAD

**Issue by porres** [porres/pd-cyclone#359]
from https://github.com/porres/pd-cyclone/commit/e3f66c49031a561f7bcff1f1464f60ee6cc9ce25

**Comment by amurtet** [comment]
I have no idea about how implement the defer method without breaking determinism. actually, the defer method is implemented using a clock function, so [loadmess @defer 1] is equal to [loadmess] --> [delay 0]. the delay time is set to 0 ms. using the delay time equal to 0 the loadmess defered is put at the scheduling but in the same logical time. this seems the most elegant solution. there are at least three strategies: leave things as are now, delete the defer method, think to other solutions. the solution that I was thinking about was to write a queue with a two-level priorities and to bind all the loadmess with this queue. however it opens several questions: e.g. you have asynchronous events. finally, I delete a pointer what was useless. this allows to remove the "hammer/file.h" dependence. I tried it successfully on OSX.

**Comment by porres** [comment]
you mean about the code I've merged in from https://github.com/porres/pd-cyclone/commit/e3f66c49031a561f7bcff1f1464f60ee6cc9ce25 right?

**Comment by amurtet** [comment]
the second one I send you.

**Comment by porres** [comment]
>  I delete a pointer what was useless. this allows to remove the "hammer/file.h" dependence. I tried it successfully on OSX.

this is present here, right? So it's just a cleaner code, huh?

Can you make a pull request for that other second one?

**Comment by porres** [comment]
ok, so now we have a new loadmess version to test here https://github.com/porres/pd-cyclone/pull/360#issuecomment-350802942

Now, about the one from https://github.com/porres/pd-cyclone/commit/e3f66c49031a561f7bcff1f1464f60ee6cc9ce25 - I don't understand what you did, you only commented out wherever there was a 'hammer' thing, but how was that removed from the code? I mean, how did you delete that pointer? Was it just totally unnecessary?

**Comment by amurtet** [comment]
e3f66c4 is just the cleaner code. hammer stuff was totally unnecessary.

**Comment by porres** [comment]
ok, then there's nothing to test but the new unmerged/untested code, I'm closing this issue and opening a new one
