### ISSUE TITLE
Could [active] work from different patch-levels?

### ISSUE THREAD

**Issue by LGoodacre** [porres/pd-cyclone#373]
A feature request here--it would be great if [active] could sense whether the window of a parent patch is active or not. In keeping with the iemguts library, this could be done with a numerical argument, ie. [active 1] senses the parent patch, [active 2] the grandparent patch, etc. Would be be feasible?

**Comment by porres** [comment]
this would break max compatibility, so something like that has a place maybe in another library... now, you can achieve this with iemguts, right? so there you have it... but then is the reason to include this functionality to remove this dependency?

**Comment by LGoodacre** [comment]
I just meant that iemguts follows the convention of using numerical arguments to refer to parent-level patches. I'm not aware of another object in iemguts or any other library that serves the same function as [active].

**Comment by LGoodacre** [comment]
But I see the point about Max compatibility.

**Comment by porres** [comment]
> I just meant that iemguts follows the convention of using numerical arguments to refer to parent-level patches. I'm not aware of another object in iemguts or any other library that serves the same function as [active].

I could then include such an object in 'else', this is where I'm putting things that don't belong in cyclone. If you wish, you can open a request: https://github.com/porres/pd-else/issues

well, since there's not much to do here, I'm closing this issue, thanks

**Comment by porres** [comment]
now, seems your request is just for convenience, right? You can still achieve what you want with cyclone and vanilla objects, right?
