### ISSUE TITLE
zl group issue

### ISSUE THREAD

**Issue by porres** [porres/pd-cyclone#380]
say we have [zl 3 group 2] and an inoput list with 3 elements, it doesn't behave the same as if you had a 3 elements list into [zl group 2], and it should...

see below

<img width="551" alt="screen shot 2018-02-05 at 02 54 06" src="https://user-images.githubusercontent.com/5360142/35788957-f5a9e512-0a1f-11e8-94f3-c35da2703eff.png">

the one in the left gives "1 2" when we first click the message, then "3 1" & "2 3" when we click it again, and then repeats if we keep doing it.

but the one on the right gives "1 2", then "3 1" and then freezes at "2 1"

**Comment by derekxkwan** [comment]
is this a radiohead reference https://en.wikipedia.org/wiki/OK_Computer_OKNOTOK_1997_2017

**Comment by porres** [comment]
hahaha, not at all...

**Comment by porres** [comment]
fixed
