### ISSUE TITLE
accum-help.pd and number boxes

### ISSUE THREAD

**Issue by LGoodacre** [porres/pd-cyclone#393]
If you test out the [accum] object in the help file by scrolling through the "increment addition" and "increment multiplier" number boxes, you get some unexpectedly high results. The reason is because the "number2" boxes send out the same number many times while you use the mouse to scroll. So instead of accumulating " 1 2 3", you end up accumulating "1 1 1 1 2 2 2 2 3 3 3 3". This makes for a confusing helpfile! The quickest solution would be to simply replace the "number2" objects with regular "number" objects.

**Comment by porres** [comment]
done: https://github.com/porres/pd-cyclone/commit/93e8db8178f47c5cc0a645ad6778380ffa56c004
