### ISSUE TITLE
New object request [ddg.mono]

### ISSUE THREAD

**Issue by alfonso73** [porres/pd-cyclone#394]
Hi!
Would be great to have [ddg.mono] in cyclone because the whole MIDI note management for mono/legato with different note priorities (last/low/hi) would be very usfeful in pd.
best!
a.

**Comment by porres** [comment]
> the whole MIDI note management for mono/legato with different note priorities (last/low/hi) would be very usfeful in pd.

agreed, if we don't do it here in cyclone, I might at least do something like that in my other library (else). I only say that because we have many priorities in cyclone 0.3 before adding more externals

**Comment by porres** [comment]
done it as a vanilla abstraction, based on my work for [else]. Please don't get used to this

https://github.com/porres/pd-cyclone/commit/73fa4696519cd0d72097331aad979a07270c43a9

**Comment by porres** [comment]
you know, I thought about it and I don't think it should be included now, as it was an abstraction and I'd rather it were a compiled object, moreover, it's not 100% like the original and I don't really like the original design and would rather have the other version I wrote for "ELSE", so, I don't think this belong here in cyclone, but if anyone thinks differently, say so...

**Comment by alfonso73** [comment]
@porres Your else abstraction works pretty good. Would be useful to have it ddg.mono for porting max patches to pd tho..

**Comment by porres** [comment]
the problem is that this wasn't mimicking correctly max's object, and it would probably be best to go to a compiled code instead, but at this point, I'm not personally motivated to do that, as we have other priorities. Of course it'd be good to have virtually all of max's object in cyclone, and anyone is welcome to collaborate and give us code for that.
