### ISSUE TITLE
Cyclone objects crash PD while running on Raspberry Pi

### ISSUE THREAD

**Issue by kroaton** [porres/pd-cyclone#395]
Hi,

First of all, I'd like to say that Cyclone is amazing and it's really breathing some new (and much needed) life into the PureData community.

For the last few weeks I've been writing a sequencer for one of my midi controllers on 64bit Linux Manjaro and now I'm trying to get it up and running on a Raspberry Pi Zero W running Raspbian Stretch (March 2018 - Kernel Version 4.9)

I've installed the latest release of Cyclone ( cyclone03beta3_RaspberryPi), I see that it's up and running (due to the startup log message) but every object I've tried so far crashes PureData almost instantly.
Counter seems to be the exception, as it only crashes when it sometimes reaches the end of it's count.

Zexy works fine, there is ample free memory so the problem seems to be with this release of Cyclone.

What can I do to help debug this issue? Cheers.

**Comment by kroaton** [comment]
It might end up just being user error, as the PD version that is available in the Raspbian repository is 0.47.1 and not the required 0.48.1

I will post back after I test it all out though this most likely was a non-issue.

**Comment by kroaton** [comment]
Tested it out on 0.48.1 with the same results. Cyclone crashes PD every time.

**Comment by kroaton** [comment]
Tried the one you highlighted and I get the "can't load library" message even with all of the paths set correctly (tried dumping it in the same place as a patch and still nothing) but it just hit me that the Raspberry Pi Zero W is armv6 and the release binaries are for armv7 so maybe that is the problem?

I tried compiling from source on my machine (thinking that it'd compile for armv6 in place of armv7) but I couldn't get it to compile properly.

------------

Commands I ran:

git clone https://github.com/porres/pd-cyclone.git
cd pd-cyclone
git submodule update --init
make pdincludepath=~/pd-0.48-1/src//home/pi/Desktop/pd-0.48-1-armv6/src

-------------------
Error output:

++++ info: making shared/magicbit.o in lib cyclone
cc -DPD -I "/root/pd-0.48-1/src//home/pi/Desktop/pd-0.48-1-armv6/src" -DUNIX  -fPIC -Ishared -DHAVE_STRUCT_TIMESPEC -Wall -Wextra -Wshadow -Winline -Wstrict-aliasing -O3 -ffast-math -funroll-loops -fomit-frame-pointer -march=armv6 -mfpu=vfp -mfloat-abi=hard -o shared/magicbit.o -c shared/magicbit.c
shared/magicbit.c:6:22: fatal error: g_canvas.h: No such file or directory
 #include "g_canvas.h"
                      ^
compilation terminated.
pd-lib-builder/Makefile.pdlibbuilder:899: recipe for target 'shared/magicbit.o' failed
make: *** [shared/magicbit.o] Error 1

Cheers.

**Comment by kroaton** [comment]
My PD path was wrong. I had a "~" in front of the path that was adding a "/root/" at the beginning of the path.

make pdincludepath=/home/pi/Desktop/pd-0.48-1-armv6/src got it compiling instantly (weird that I didn't get an error about this upfront before)

It seems to be stable and working properly now, so mismatch between armv6 / armv7 was the problem.

Cheers.

**Comment by porres** [comment]
great, I can close this issue then. But note that you have to do "make install -objectsdir=../" so it'll create a cyclone folder in the parent directory with all you need in it. Can you do that and send us the compressed file? We can then include it in deken and also in here for download

**Comment by kroaton** [comment]
Sure. I'll re-compile and send them over tomorrow.
