### ISSUE TITLE
errors with re-making

### ISSUE THREAD

**Issue by derekxkwan** [porres/pd-cyclone#41]
Noticed this while testing scope~:

When I've already built cyclone and I'm trying to re-build by typing "make" without "make clean"-ing first, I run into errors (which hasn't happened before today).

`++++ info: using Pd API /usr/include/pd/m_pd.h
++++ info: making target all in lib cyclone
++++ info: evaluating implicit prerequisites in lib cyclone.....
cc: error: shadow/cyclone: No such file or directory
cc: fatal error: no input files
compilation terminated.
Makefile.pdlibbuilder:906: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.
`
I'm not sure what the complaint is about in Makefile.pdlibbuilder but that section is defining must-build-everything.

I'm also noticing that shadow/cyclone.c has had some changes done to them recently, could this be what the other warning is about?

**Comment by porres** [comment]
cyclone.c is restored to "untouched state", sorry, I was making some tests, but that doesn't seem to be it.

and I actually always had that kind of problem here since I started working on this, funny you didn't have it and suddenly started to.

well, at least it builds :)

**Comment by porres** [comment]
cyclone.c is restored to "untouched state", sorry, I was making some tests, but that doesn't seem to be it.

and I actually always had that kind of problem here since I started working on this, funny you didn't have it and suddenly started to.

well, at least it builds :)

we can always compare to https://github.com/electrickery/pd-miXedSon - if nothing had changed ;)

**Comment by porres** [comment]
@derekxkwan - did you ever get this sorted? you should know better than me :) - can you maybe discuss it with @katjav?

**Comment by porres** [comment]
well, I guess just use "make clean", and I'm closing this :)
