### ISSUE TITLE
cyclone/ prefix

### ISSUE THREAD

**Issue by nburge** [porres/pd-cyclone#422]
Hello, I just installed cyclone to my raspberrypi running the latest pd vanilla (0-48.1) I notice that all the helpfile objects have a cyclone/ prefix. If I remove the prefix the object loads, otherwise not. Path is set correctly and pd reports the library as loading correctly as it starts. Is there a way to fix this without laboriously removing all the object prefixes? Thanks. Nick.

**Comment by porres** [comment]
hi, you need to:

1) install cyclone somewhere else, like in ~/Pd/externals folder (I don't know what or where this folder is in raspbery, but that's the folder Pd 0.48-1 asks you to create and where Pd would automatically download externals to, if you didn't do things differently.

or

2) For some whatever reason you don't want to create or use that folder and put cyclone there. Then just include whatever folder the cyclone library is in into Pd's path (Preferences => Path).

anyway, this should do it, and here's a wiki on how to install cyclone for more info and details https://github.com/porres/pd-cyclone/wiki/How-To-Install

**Comment by nburge** [comment]
Thank you for your attention to this. It seems to be a raspberrypi issue as the library loads objects perfectly well on osx regardless of whether the object has cyclone/ as prefix or not. Meanwhile on my Pi I've moved the cyclone external library to ~/Pd/externals reset the paths and still the objects only load if I delete the "cyclone/" prefix. Guess I'll just have to work with it.

**Comment by porres** [comment]
you should then open an issue on . pure data https://github.com/pure-data/pure-data/issues

**Comment by porres** [comment]
I'm sure it will be sorted if you bring it up there and in the Pd List

**Comment by nburge** [comment]
Thank you, I just posted my question to the pd-list
