### ISSUE TITLE
cyclone: can't load library - "undefined symbol: setup_single_lib" - Raspberry Pi

### ISSUE THREAD

**Issue by Sciss** [porres/pd-cyclone#434]
Hi,

I tried "find externals" but there seems no build for arm32, so I build from source. I have built and installed pd 0.49-0 without problems. What I did for cyclone:

    mkdir -p ~/Documents/devel
    cd ~/Documents/devel
    git clone https://github.com/porres/pd-cyclone.git
    cd pd-cyclone
    make pdincludepath=/home/pi/Documents/devel/pure-data/src/
    make install objectsdir=../cyclone-build
    mkdir -p ~/Documents/workshop/pd/externals
    mv ../cyclone-build/cyclone ~/Documents/workshop/pd/externals

I have `~/Documents/workshop/pd/externals` in Pd search path. I add Preferences -> Startup -> New -> `cyclone`. I quit and restart pd. It tries to load cyclone but fails:

    /home/pi/Documents/workshop/pd/externals/cyclone/cyclone.pd_linux: /home/pi/Documents/workshop/pd/externals/cyclone/cyclone.pd_linux: undefined symbol: setup_single_lib
    cyclone: can't load library

I have no idea why it's failing. Any clues?

![screenshot of raspberrypi at 2019-02-04 22 32 36](https://user-images.githubusercontent.com/131300/52238767-1ce9c580-28cd-11e9-9a21-695cbe877db1.png)

**Comment by porres** [comment]
hi, can you load externals that don't need to be called from the cyclone lib binary? These are just the vast majority of externals! Just add the cyclone folder to the path, open the help files and see.

We need to investigate what the "undefined symbol: setup_single_lib" means, let me check the code in the meantime.

**Comment by porres** [comment]
Oh... "setup single lib", nah, that's bad - you should be using "cyclone_lib.c".

This is actually something somebody else included here, but it's gonna make it more complicated, I'll just take it out...

try compiling from the last stable release https://github.com/porres/pd-cyclone/releases/tag/cyclone0.3rc1

**Comment by porres** [comment]
yup, I accepted a change from a third party that screwed things over :) - I can't load the library either... I'm sorting this out now.

**Comment by Sciss** [comment]
Ok, thanks for the quick response. Can I just try to build from an older commit? Which commit should I perhaps try?

**Comment by porres** [comment]
arm32, what is it for? raspberry pi?

**Comment by Sciss** [comment]
Yes, Raspberry Pi 3B+

**Comment by porres** [comment]
I think I can compile for that now, see if you can find else 1.0 beta 15 and 16 in find externals, and if they work - If so, next cyclone release will have that up in deken ;)

**Comment by porres** [comment]
anyway, this seems to have fixed this, you can try compiling from the latest source now if you will https://github.com/porres/pd-cyclone/commit/42f5dcec7b205a2b0c9e0fcbd7e641faa2061a4d

**Comment by Sciss** [comment]
Ok, cool. I will try. BTW LOL we have similar avatars :)

**Comment by porres** [comment]
well, mine is actually my own skull via a MRI scan

**Comment by Sciss** [comment]
mine is from a previous life a few centuries ago.

Anyway - it works now, thanks! :tada:

**Comment by porres** [comment]
Hey, tell me if you can download and use the objects from ELSE, so next time I know you'll also find cyclone for download (we should have a new cyclone version coming soon).

**Comment by Sciss** [comment]
I don't know how do to that. Help -> Find Externals does not find `cyclone` if you mean that. But I don't know ELSE (I'm not a regular Pd user).

**Comment by Sciss** [comment]
it finds externals called `else[v1.0beta16].dek`

**Comment by porres** [comment]
Try **Help -> Find Externals** - then find `else`

this is just another library, and I have recently succeeded in compiling it for raspberry Pi and uploading it to deken. But I don't have a Pi to test it...

**Comment by Sciss** [comment]
I get this:

> Unable to download from http://puredata.info/Members/porres/software/else/1.0beta16/else%5bv1.0beta16%5d.dek [HTTP/1.1 404 Not Found]

**Comment by porres** [comment]
yeah, that's not good, you should have seen something like this 
<img width="411" alt="screen shot 2019-02-04 at 20 12 23" src="https://user-images.githubusercontent.com/5360142/52240847-3aad2f80-28b9-11e9-89f6-e406d745b231.png">

so it seems your pi is not arm7, maybe it's arm8?

**Comment by Sciss** [comment]
$ uname -a
    Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

**Comment by Sciss** [comment]
Pd might be confused. If I go Find externals -> Preferences, it says

> Platform settings:
> (*) Default platform: Linux-armv6-32
> ( ) User-defined platform:

Should I change that?

**Comment by porres** [comment]
yeah, you don't have armv6, right? :) try making it show "foreign architectures" then download and test those externals... but if Pd seems confused, we need to open an issue there ;)

**Comment by porres** [comment]
you can also try uploading your cyclone build to deken, or at least package it and see what you get (surely armv7)

**Comment by Sciss** [comment]
If I manually set `Linux-armv7-32`, it shows `else[v1.0beta16](Linux-armv7-32).dek`. It downloads it correctly. Do I need to add another startup item, like `else`?

**Comment by porres** [comment]
nope, just add a path and have fun :)

**Comment by porres** [comment]
armv6 is just the 1st raspberry pi ever, right?

**Comment by Sciss** [comment]
No idea. Yup, adding `else` to paths works. Checking out `hann~`, seems all good, great!

**Comment by porres** [comment]
anyway, you should really open an issue at https://github.com/pure-data/deken/issues saying that the latest Pd defaults to the wrong architecture in the Pi!

**Comment by Sciss** [comment]
Ok. BTW: https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications  I have underspec'ed raspbian I guess, it should be armv8 already
