### ISSUE TITLE
[past] bug

### ISSUE THREAD

**Issue by emviveros** [porres/pd-cyclone#44]
[past] bug: [bug-past.pd.zip](https://github.com/porres/pd-cyclone/files/220317/bug-past.pd.zip)

**Comment by porres** [comment]
[past] is quite messy indeed! It's very screwed up in max and in PD... 

Not only there is a bug in Pd already, but Pd is trying to replicate completely nonsensical buggy behaviour from max resulting in a great effort to document how the buggy behaviour works instead of providing max's actual documentation and an object that just does it.

As usual, I don't think we have to reverse engineer Max's bugs, it's better to say, if anything, that the max version is buggy

**Comment by porres** [comment]
we find this pearl in the documentation of pd-extended 0.42-5 

"this is a quote from an email Krzysztof Czaja sent me:
> it's list handling is weird indeed, it bangs if _any_ list
> item is greater than (>) a corresponding threshold, or if
> _all_ list elements are greater or equal (>=). That is how
> it looks like in Max but I might be wrong ..."

I checked it, and no... it is not like that in Max

so not only it's maybe trying to replicate Max's bugs, but it's doing it wrong...

we should fix this mess and just make it simple and not "weird" at all

after all, who needs "weird" behaviour when all it does is just completely screw up the purpose of the object?

**Comment by porres** [comment]
I'll only make one small change to the float method to make it consistent to the list behaviour and I'll document this change and better document the list behaviour without changing it. Thus, changes won't be too drastic but it'll make much more sense now and won't be confusing anymore

**Comment by porres** [comment]
on second thought... having a better look, keeping the list behaviour is so stupid, cause it kinda just makes it completely useless or redundant, cause you can still send it a list where only the first element is >= the 1st argument and it just kills the idea of comparing a list, as it is the same result as sending it just a float...

it's really much better to fix this object and make it work in a sensible and functional way thanjust have an useless garbage around...

sorry... I tried to keep things as they were... it's just really pointless!

**Comment by emviveros** [comment]
Really great! Correct objects are better than bugged objects.. Ever.. (or not). hehehe

I can't see better on have a object making comparisons and it do it in a wrong way forcing the programer to think additional code to have correct behavior.

thanks!

**Comment by porres** [comment]
well, basically, for now, if you want to compare lists to [past], you can't!

it's better if you actually can :)

**Comment by emviveros** [comment]
yep!! :)

**Comment by porres** [comment]
well, fixed some of it but I still need help, I'll close this issue, as there was no real bug, and will open a new one...
