### ISSUE TITLE
bucket missing from cyclone v 0.3 for linux?

### ISSUE THREAD

**Issue by porres** [porres/pd-cyclone#453]
is it?

**Comment by tommyecho** [comment]
Hi! I'm running puredata .49 on Raspbian buster with the cyclone objects v 0.3 running and, for some reason, the bucket object is not present in the browser. When I try to create a bucket object, it is not recognized by puredata. 

Is anyone else having this problem?

Thanks!

tom

**Comment by porres** [comment]
we seem to confirm this, will fix in a new update in a couple of weeks

**Comment by porres** [comment]
as soon as pd 0.50.0 is out

**Comment by porres** [comment]
We've uploaded a new package to deken with aliases for 'Bucket' and others. But not for raspberry pi yet... are you on raspberry only @tommyecho ? Can you test the new linux 64 package? Or, anyway if you can use 'bucket' on raspberry?

**Comment by porres** [comment]
anyway, I'm now releasing 0.4 and we have no more capital letters aliases any longer, so I'm closing this issue

**Comment by tommyecho** [comment]
Hi Alexander,

Sorry to just get to this.  I had a performance today and have been busy composing g for it in my free time. I should have some time this week to check this out. This month is a bit hectic

This message was sent from my 
Phone.

**Comment by porres** [comment]
check it and check also the new version that's coming out today :)

**Comment by tommyecho** [comment]
Awesome! Will do! Thanks!!!

This message was sent from my 
Phone.
