### ISSUE TITLE
seq:  "got 1 midi tracks (out of 2)" when help file says it's supposed to merge all tracks into one

### ISSUE THREAD

**Issue by dfkettle** [porres/pd-cyclone#462]
I'm not really sure if this is a bug or just a misunderstanding on my part, but when reading a MIDI file with two tracks, [cyclone/seq] writes a message to the console saying "got 1 midi tracks (out of 2)". The help file says that it's supposed to merge all tracks into one. This is under cyclone v0.4 and pd v0.50.0 (32-bit) and  on Windows 7 Home Premium, SP 1.

Here's a link to the MIDI file (which I downloaded from some web site, I don't remember where):

https://www.dropbox.com/s/kmb4jzmbusyk7jl/Gymnopedie1.mid?dl=0

Here are screen shots of the patch and the system console after clicking on the [read( message and selecting the MIDI file:

![Screenshot 2019-10-06 12 03 12](https://user-images.githubusercontent.com/8409615/66271938-ac1af480-e831-11e9-8b75-11b696ddaf3c.png)
![Screenshot 2019-10-06 12 04 21](https://user-images.githubusercontent.com/8409615/66271939-ac1af480-e831-11e9-9a54-e5d8d15db9ba.png)

**Comment by porres** [comment]
other issues
---------------

- missing dump method, which I don't get or care for

Dump: Opens a standard Open Document dialog box, to select a saved sequence or standard MIDI file. The selected file is opened as text in a new Untitled text window, which can be edited and saved.

https://docs.cycling74.com/max7/maxobject/seq

---------------

more? 
- Max 7.3.2 supports MIDI Type 1 (separate information for each track). Cyclone already does this but doesn't seem to save type 1 (don't know how max saves midi files. Anyway, this seems nothing to worry...)

- [seq] has extra methods/features not available in max and that were not documented even in cyclone. It's hard to know what some are supposed to do and if they work at all or not... so this not supported (yet). Seems like Czaja had plans of a super sequencer (which may have become another project [xeq]?). Anyway, there's a need to figure this out and know what to do with them.

---------------

**Comment by porres** [comment]
also... Max 7.3.2 says it now supports MIDI Type 1 (separate information for each track). Cyclone already does this but doesn't seem to save type 1 (don't know how max saves midi files), see https://github.com/porres/pd-cyclone/issues/258

**Comment by porres** [comment]
also... Max 7.3.2 says it now supports MIDI Type 1 (separate information for each track). Cyclone already does this but doesn't seem to save type 1 (don't know how max saves midi files).

**Comment by porres** [comment]
> https://www.dropbox.com/s/kmb4jzmbusyk7jl/Gymnopedie1.mid?dl=0

this item has been deleted. You should have just uploaded the midi file as a zipped attachment to this page.

I'll start a new issue
