### ISSUE TITLE
[cyclone/seq] in Purr Data & Pure Data Vanilla

### ISSUE THREAD

**Issue by joe-rouen** [porres/pd-cyclone#464]
Hello Alexandre,

I would like to get your thinking about these 2 posts I wrote on Purr Data's GitLab regarding big issues I'm facing to with [cyclone/seq], mainly with SysEx-Out traffic but not only.

- [Cyclone v.0.2 issues with MIDI & forthcoming v.0.3/0.4](https://git.purrdata.net/jwilkes/purr-data/issues/554)

- [Thread 1 "purr-data" received signal SIGSEGV](https://git.purrdata.net/jwilkes/purr-data/issues/555)

I would really appreciate your comments, so I can report your valuable technical arguments to Purr Data developers with more strengths that only my humble opinion.

Thank you very much.
Joseph

**Comment by porres** [comment]
Hi, we don't really have anything to do with Purr Data's development. Unfortunately, there are some issues in Purr Data that need work so it can include the latest cyclone versions.

Anyway, if you have an actual issue related to cyclone's seq, just open another one

cheers
