### ISSUE TITLE
[zl delace] not working under Windows 7

### ISSUE THREAD

**Issue by HenriAugusto** [porres/pd-cyclone#465]
**On Windows7:** I've tested with cyclone v0.3 and cyclone v0.4 and [zl delace] only outputs to it's left outlet.

**OSX 10.13.6**: Works normally.

I couldn't test with Linux yet.

**Comment by porres** [comment]
> I couldn't test with Linux yet.

I did, it's bugged like windows

**Comment by porres** [comment]
found compilation warnings for delace

cyclone_objects/binaries/control/zl.c:960:20: warning: unsequenced modification
      and access to 'i' [-Wunsequenced]
                        buf[i/2] = av1[i++];
                            ~           ^
cyclone_objects/binaries/control/zl.c:961:21: warning: unsequenced modification
      and access to 'i' [-Wunsequenced]
                        buf2[i/2] = av1[i++];

**Comment by porres** [comment]
it seems delace doesn't work with an odd number of elements

**Comment by porres** [comment]
please try it now, it did work on linux for me

**Comment by porres** [comment]
I also fixed a bug where odd number weren't working well
