### ISSUE TITLE
no foreign languages are supported in [cyclone/comment]

### ISSUE THREAD

**Issue by H-MLim** [porres/pd-cyclone#494]
I just tested [cyclone/comment] with very newest version of cyclone and it still crashes when I write any comments on any foreign languages except English. would it be fixed?
(but no problem at default comments via Ctrl+5)

(by the way I told to porres that Pd freezes when I grow up the font size but it didn't happen when tested today again.)
![COMMENTE](https://user-images.githubusercontent.com/68152553/87224720-89220000-c3c2-11ea-90e8-3f58ebf66064.JPG)

**Comment by porres** [comment]
yeah, typing directly into cyclone/comment doesn't work, this is known. But can you type all this elsewhere in Pd vanilla??????????????????????????? Like a message box???????????????????

The only way out now is that if you can connect a message to cyclone/comment so you can set it with a different alphabet, via the "set" method. So you can do something like this (but i did not typre directly in it).

<img width="378" alt="Screen Shot 2020-07-11 at 13 03 38" src="https://user-images.githubusercontent.com/5360142/87228345-0031a700-c377-11ea-9edf-c226aeafc52d.png">

anyway, if it's just a matter that comment doesn't allow you to type in with foreign alphabets, this is a known issue and I'm trying to fix it. This is also already listed as one of the bugs in https://github.com/porres/pd-cyclone/issues/436 so I would close this issue if that's just it.

thanks

**Comment by porres** [comment]
I don't seem to get japanese (katagana) working on vanilla...
