### ISSUE TITLE
Failed to cross compile Cyclone 0.5-3 to Win

### ISSUE THREAD

**Issue by emviveros** [porres/pd-cyclone#500]
Cross compile failed when compiling cyclone. Host machine: Ubuntu 20.04 running in virtual box.

Compilation stops in coll. I ran:

`make PLATFORM=i686-w64-mingw32 PDDIR='/home/pi/src/pd-compilados/win/pd-0.51-1-i386' install objectsdir=../cyclone_0.5-3_Win32`

here compilation log: [log_w32.txt](https://github.com/porres/pd-cyclone/files/5121550/log_w32.txt)

when trying to compile for w64 it returns error to:
`make PLATFORM=x86_64-w64-mingw32 PDDIR='/home/pi/src/pd-compilados/win/pd-0.51-1' install objectsdir=../cyclone_0.5-3_Win64`

compilation log: [log_w64.txt](https://github.com/porres/pd-cyclone/files/5121565/log_w64.txt)

I used windows zip binaries from miller's site
for win32: http://msp.ucsd.edu/Software/pd-0.51-1-i386.msw.zip
for win64: http://msp.ucsd.edu/Software/pd-0.51-1.msw.zip

**Comment by Lucarda** [comment]
Hi,
Can you test this PR on branch: https://github.com/Lucarda/pd-cyclone/tree/cross-fix

It should finish the compilation with no issues but you have to manually include the file `libwinpthread-1.dll` from your compiler to the `cyclone` folder. Be careful as there are 2 files with the same name. One is 32bit and the other 64bit.

**Comment by porres** [comment]
merged, test it please @emviveros

**Comment by porres** [comment]
@Lucarda, would you change the readme to include the proper information about this issue?

**Comment by emviveros** [comment]
@Lucarda, the cross-compilation are completed successful for both, 32bits and 64bits.

I copied `/usr/i686-w64-mingw32/lib/libwinpthread-1.dll` to cyclone folder and ran: `make PLATFORM=i686-w64-mingw32 PDDIR='/home/pi/src/pd-compilados/win/pd-0.51-1-i386' install objectsdir=../cyclone_0.5-3_Win32` for 32bit cross-compilation

and copied '/usr/x86_64-w64-mingw32/lib/libwinpthread-1.dll' to new cyclone folder and ran: `make PLATFORM=x86_64-w64-mingw32 PDDIR='/home/pi/src/pd-compilados/win/pd-0.51-1' install objectsdir=../cyclone_0.5-3_Win64` for 64bit cross-compilation.

These libwinpthread-1.dll files are from mingw-w64 ubuntu package install via apt.

**Comment by emviveros** [comment]
These procedure is a default behavior? 

I will need to link these files every compilation or these linking can be made automatically by pd-lib-builder PLATFORM  variable?

**Comment by Lucarda** [comment]
> I will need to link these files every compilation or these linking can be made automatically by pd-lib-builder PLATFORM variable?

I'm finishing a new PR to do this automatically.

:)

**Comment by porres** [comment]
merged :) go ahead and test it @emviveros  ;)

**Comment by emviveros** [comment]
@porres, Cross compiling like a boss! 👍 

Thanks a lot @Lucarda !
