### ISSUE TITLE
creating cyclone/Scope~ (uppercase S) before creating a cyclone/scope~ (lowercase s) crashes pd

### ISSUE THREAD

**Issue by sebshader** [porres/pd-cyclone#538]
edit: actually this occurs even when cyclone is loaded
from the crash report:
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   Scope~.pd_darwin              	0x000000010d5af0b4 scope_new + 292
```

oddly enough I don't see a Scope~.pd_darwin file.. I guess pd looks in scope~.pd_darwin and finds Scope_tilde_setup

this doesn't happen with cyclone/scope~
perhaps it is has something to do with Scope_tilde_setup not setting up the edit proxy class where scope_tilde_setup does:
```
edit_proxy_class = class_new(0, 0, 0, sizeof(t_edit_proxy), CLASS_NOINLET | CLASS_PD, 0);
class_addanything(edit_proxy_class, edit_proxy_any);
```
but then edit_proxy_new is called in scope_new
perhaps the compiler inlined the contents of edit_proxy_new and/or pd_new (pd tries to reference members of edit_proxy_class in pd_new without having allocated memory for the class with class_new)?

**Comment by porres** [comment]
what is your system, your pd version, etc?

I can't seem to reproduce

**Comment by sebshader** [comment]
MacOs 10.14.6. it happens with pd 0.51.0 and 0.51.2

are you sure you can't reproduce? you can't have already created cyclone/scope~ in the pd session.
steps:
1. start pd
2. open canvas
3. attempt to create [cyclone/Scope~]

**Comment by porres** [comment]
ok, I see it now, for some reason :)

**Comment by porres** [comment]
it's been about 4 years we've been tryi ng to get this damn thing right

**Comment by porres** [comment]
fixed, but please, just change your patches to "scope~" instead ;)
