### ISSUE TITLE
Possible problem with [seq] when recording and saving a sequence

### ISSUE THREAD

**Issue by dfkettle** [porres/pd-cyclone#543]
I'm not sure if this is a bug or just a lack of understanding on my part, but it seems that when recording and saving a MIDI sequence, the last note isn't written out to the file correctly. If I send a "print" message to [seq], all the data seems to be there (assuming a sequence of less than 16 events), but when I play back the MIDI file, the last note is cut off or doesn't play at all. Maybe a buffer isn't being flushed or something?

I found a work-around by adding an extra note-off to the sequence at the end, so it's not a big problem.

![MIDI-recording](https://user-images.githubusercontent.com/8409615/104739114-59a6d400-5714-11eb-9ea9-e28f013cef01.jpg)

**Comment by dfkettle** [comment]
It also appears (although I'm not sure about this) that the first note in the sequence isn't getting written to the file either.

**Comment by porres** [comment]
hi, please provide a minimal patch that shows the issue

**Comment by dfkettle** [comment]
Here's a patch that records 3 notes. When I click on the "print" message, I see all 3 notes in the PD console window. But when I save it to a file, I only see 1 of them in the file when I open it in a text editor.

![screen1](https://user-images.githubusercontent.com/8409615/104762061-c2507980-5731-11eb-9bbf-c3257ca69e0e.jpg)
![screen2](https://user-images.githubusercontent.com/8409615/104762065-c2e91000-5731-11eb-8494-65abb8ba4b21.jpg)
![screen3](https://user-images.githubusercontent.com/8409615/104762066-c2e91000-5731-11eb-8858-9cd086160462.jpg)

**Comment by porres** [comment]
I meant I need you to send/upload a patch so I can test

**Comment by dfkettle** [comment]
Sorry, misunderstood. Github wouldn't let me upload a file with the extension 'pd', so I uploaded it as a text file.

[test-seq.txt](https://github.com/porres/pd-cyclone/files/5822615/test-seq.txt)

**Comment by dfkettle** [comment]
I don't know if you want me to open another issue for this, but the help file shows an example of sending [play( to [seq], but when I tried it, I got an error message, "seq: no method for 'play'". Sending it a bang still works, though.

![screen4](https://user-images.githubusercontent.com/8409615/104774263-57f50480-5744-11eb-9ee4-d6ce6f3e6a6a.jpg)

**Comment by dfkettle** [comment]
Ignore the example I posted above, I see the three notes now. I thought 2 of them were missing because the "note on" byte (x'89') was omitted for the 2nd and 3rd notes. But I still think there's a problem in formatting the MIDI file. I'll try to come up with a better example.

**Comment by porres** [comment]
> But I still think there's a problem in formatting the MIDI file. I'll try to come up with a better example.

i'll close this then... you can recreate the issue, and when you upload the patch you can send a .zip file instead
