### ISSUE TITLE
[seq] object doesn't recognize "play" message

### ISSUE THREAD

**Issue by dfkettle** [porres/pd-cyclone#544]
The help file for [seq] gives an example of a "play" message being sent to [seq], but when I try it, an error msg ("seq: no method for 'play'") is displayed.

Help file:

![Image2](https://user-images.githubusercontent.com/8409615/104811869-7ef71900-57cc-11eb-8014-64fe2717f62f.jpg)

Simplified example:

![Image1](https://user-images.githubusercontent.com/8409615/104811900-9df5ab00-57cc-11eb-9226-fab2ba9642f4.jpg)

Console window (note that the [seq] object contains data):

![Image3](https://user-images.githubusercontent.com/8409615/104811909-bc5ba680-57cc-11eb-89b9-70c4d4e11088.jpg)

Test patch and MIDI file input:

[seq-bug-1.zip](https://github.com/porres/pd-cyclone/files/5824366/seq-bug-1.zip)

**Comment by porres** [comment]
yeah, [seq] does not have a "play" message listed in the patch's main window. So this is an error and I'm fixing it and replacing it by a bang.
