### ISSUE TITLE
Possible problem with [seq] when recording and saving a sequence (follow-up to issue #543)

### ISSUE THREAD

**Issue by dfkettle** [porres/pd-cyclone#545]
I think I understand what's going on now, and I'm not sure whether to consider this a bug in [seq] or just a quirk of MIDI. It looks as if the last note in a sequence, although it gets saved in the MIDI file, sometimes doesn't play, or gets cut off before the note is finished. But if you add an event after the last note, allowing enough time for the note to finish, it plays properly. Maybe this is the way MIDI files are supposed to work, I don't know.

For example, if you just record the first note-on, save it, and then play the file (I'm using Windows Media Player for this), you won't hear the note. But if you record the first note-on, wait long enough for the note to fade out, then record the second note-on (with a velocity of zero), both events get saved to the file and you hear the note when you play it back.

If this is the way MIDI is supposed to work, then I think it's a problem in the MIDI file standard itself. But if there's something that can be done to get around the problem, it might save users some trouble. 

![Image1](https://user-images.githubusercontent.com/8409615/104821081-6ce69c00-5807-11eb-9472-bf8c7e424873.jpg)

I've attached the patch used to create the files, as well as the two output files, the first one with just the first note-on and the second one with both.

[seq-bug-2.zip](https://github.com/porres/pd-cyclone/files/5825036/seq-bug-2.zip)

**Comment by porres** [comment]
yeah, you can't just have a note on and I don't see a bug.

you should just use [cyclone/midiformat] and things like [makenote] to record stuff into [seq], making sure it has note offs.

you can also try [else/midi] and [midifile]

**Comment by dfkettle** [comment]
Thanks, I didn't think the note off event was required (since the sounds I'm triggering will fade out anyway). I've generated files with many note on events, but no note off events and they play properly, except for the last note.
