### ISSUE TITLE
Capital letters aliases in Linux

### ISSUE THREAD

**Issue by porres** [porres/pd-cyclone#553]
all of the linuxes downloads from deken in version 0.5-5 are screwed.

We don't have capital letter aliases, see => https://github.com/porres/pd-cyclone/blob/master/Makefile#L328

Scope~, Bucket, Clip~, Peak, Table, Trough are capitalized somehow, they should be with lower case letters and should include Capital letters aliases

btw, I don't see this working for cyclone 0.2 or 'nilwind' either, more tests needed

cyclone v0.0.extended seems to work with aliases (it provides aliases for lower case letters though, we're attempting to do the opposite, capital letters aliases)

**Comment by mxa** [comment]
When creating a `[cyclone/Scope~]` you get the warning:
```
warning: class 'cyclone/Scope~' overwritten; old one renamed 'cyclone/Scope~_aliased'
Cyclone: please use [scope~] instead of [Scope~] to supress this error
```
even though it creates successfully. However, `[cyclone/scope~]` is not creating.

![image](https://user-images.githubusercontent.com/1220707/127395178-2d360593-0c7b-4e44-9995-f50fdb4d7e97.png)

**Comment by porres** [comment]
@mxa , and if you manually rename without capital letters, it works just fine, right?

**Comment by porres** [comment]
@Lucarda we had issued with capital letters and it was something you did, remember? We're still having some weird issues where some of the objects do not create aliases

**Comment by porres** [comment]
@mxa , and if you manually rename without capital letters, it works just fine, right? But then you can only create it as "scope~" and not "Scope~", right?

**Comment by porres** [comment]
@Lucarda we had issued with capital letters and it was something you did, remember? 

It was here in this commit, actually =>  https://github.com/porres/pd-cyclone/commit/0e0956bd4f65641e57ead11b4c3f7ba4743da568

Well, we're still having some weird issues! Can you help us?

**Comment by porres** [comment]
btw, I don't see this working for cyclone 0.2 or nilwind either, more tests needed

**Comment by porres** [comment]
cyclone v0.0.extended seems to work with aliases (it provides aliases for lower case letters though, we're attempting to do the opposite, capital letters aliases)

**Comment by emviveros** [comment]
Asked by @porres I start a test in Linux (virtual machine running Ubuntu 12.04).

I downloaded all these versions from deken:

### cyclone v0.0 extended - Capital letters works
![cyclone_v0 0extended](https://user-images.githubusercontent.com/3089536/127721056-2333c4e1-c6df-4e6a-9325-5268beb5be8c.png)

### cyclone v0.2beta1 - Capital letters works
![cyclone_v0 2beta1](https://user-images.githubusercontent.com/3089536/127721046-d221fe76-e3df-4018-98eb-d5c0894203c8.png)

### cyclone v0.3 - Capital letters works
![cyclone_v0 3](https://user-images.githubusercontent.com/3089536/127721052-2aa532d5-8654-41b5-b316-0371d4d6bebc.png)

### cyclone v0.4 - Capital letters don't work
![cyclone_v0 4](https://user-images.githubusercontent.com/3089536/127721051-4a7045fe-65cf-4ebb-852d-2fbfeb950597.png)

### cyclone v0.5-5 - Capital letters don't work
![cyclone_v0 5-5](https://user-images.githubusercontent.com/3089536/127721054-0072810e-a6af-458d-9e3f-ff324aff0adb.png)

### cyclone compiled from master repository - Capital letters work
![cyclone_compilado](https://user-images.githubusercontent.com/3089536/127722290-a6a54f52-53fb-4a31-9222-f1ae27382ff5.png)

**Comment by mxa** [comment]
> @mxa , and if you manually rename without capital letters, it works just fine, right? But then you can only create it as "scope~" and not "Scope~", right?

That's correct.

**Comment by Lucarda** [comment]
@porres and @emviveros  

Did cyclone v0.5-5 binaries where produced with `make install` target?

If not they should as that triggers the creation of the symlinks.

**Comment by porres** [comment]
@emviveros, test them separately, each patch with either lower case or upper case. Close Pd before and open one and then close and open another

**Comment by emviveros** [comment]
Ok. 

### Cyclone v0.0 extended
- #### Lower - Work
![Captura de Tela 2021-07-30 às 22 19 56](https://user-images.githubusercontent.com/3089536/127724322-68ea8763-6879-4724-931f-d64f00b409f4.png)

- #### Upper - Work
![Captura de Tela 2021-07-30 às 22 23 10](https://user-images.githubusercontent.com/3089536/127724341-4400e381-afc9-4397-8fbe-ad755fdcc50e.png)

---
### Cyclone v0.2beta1
- #### Lower - Work
- #### Upper - Work

---
### Cyclone v0.3
- #### Lower - Work
- #### Upper - Work

---
### Cyclone v0.4
- #### Lower - Work
- #### Upper - DON'T Work
![Captura de Tela 2021-07-30 às 22 29 56](https://user-images.githubusercontent.com/3089536/127724581-0fc9c39b-0e53-4513-8f4b-e35ef84082f1.png)

---
### Cyclone v0.5-5
- #### Lower - DON'T Work
![Captura de Tela 2021-07-30 às 22 31 54](https://user-images.githubusercontent.com/3089536/127724638-3a3c7c6e-cf7e-4d31-b258-2d265dda6c5e.png)

- #### Upper - Blow Pd if open saved patch and Work if patching
    - patching:
    ![Captura de Tela 2021-07-30 às 22 34 28](https://user-images.githubusercontent.com/3089536/127724714-291b73c0-4583-4069-b36b-9310318acf53.png)


---
### Cyclone compiled
- #### Lower - Works
![Captura de Tela 2021-07-30 às 22 18 28](https://user-images.githubusercontent.com/3089536/127724215-0986f026-1e1b-47d6-b8c3-8dcc3fd75428.png)
- #### Upper - Maybe
![lowcapitals_cyclonecompiled](https://user-images.githubusercontent.com/3089536/127724152-1fe50c4f-9f01-4f69-9c56-fcd678f97fad.png)

**Comment by Lucarda** [comment]
On my test (building from current master and running on Debian 10.1) it seems to work as expected.

I get the errors on the console but I think that's fine.

![b](https://user-images.githubusercontent.com/25239522/127724962-e6426294-72ac-4da4-bdea-b8a4dc3774e7.png)

**Comment by porres** [comment]
> I get the errors on the console but I think that's fine.

yeah @Lucarda, the errors are intentional. But can you try creating them (upper and lower case) separately (not in the same patch?)?

like I instructed esteban, kill pd then try one, kill it again and try the other.

And how exactly do things look when you build it? Do you see the proper binary and the generated alias? Does the build process tell you that it did successfully created the aliases?

**Comment by Lucarda** [comment]
> But can you try creating them (upper and lower case) separately (not in the same patch?)?

> like I instructed esteban, kill pd then try one, kill it again and try the other.

I had tested that. It works ok for me.

> And how exactly do things look when you build it? 
> Do you see the proper binary and the generated alias? 
> Does the build process tell you that it did successfully created the aliases?

This is the file explorer with the generated symlinks (alias):

![f](https://user-images.githubusercontent.com/25239522/127729669-0646a4e4-13a3-4f42-939f-3cce7e46b2ee.png)


and this is the terminal when building with `make PDDIR='/home/lucarda/Downloads/pure-data-master' PDLIBDIR=./out64 install`

![t](https://user-images.githubusercontent.com/25239522/127729675-a691b2d6-2c20-4c98-90c7-860954e44699.png)

**Comment by porres** [comment]
Great, so, @Lucarda, the way you're building it seems to work perfectly then. You gotta help us on the build process. @emviveros can also build and see if it works for him as well.

It'd be good to build this like we're building ELSE now, with just 2 packages for Linux comprising all possibilities (Arm versions and 32-64bit). Esteban knows how to do this but we need to be able to generate the links as you did.

I'm gonna put a new release right away so we can upload new versions to deken.

**Comment by porres** [comment]
here's the new tagged release version => https://github.com/porres/pd-cyclone/releases/tag/cyclone_0.5-6

@emviveros and @Lucarda, let's see if we can build this correctly for Linux. Thanks!

**Comment by Lucarda** [comment]
Here are Linux binaries in a single pkg:

[cyclone_0.5-6_Linux-i386-amd64.zip](https://github.com/porres/pd-cyclone/files/6910808/cyclone_0.5-6_Linux-i386-amd64.zip)

**Comment by porres** [comment]
> cyclone_0.5-6_Linux-i386-amd64.zip

ok, uploaded this to deken and to our 'releases' page here on github. 

@mxa, can you download 0.5-6 from deken and test?

<img width="492" alt="Screen Shot 2021-07-31 at 11 38 11" src="https://user-images.githubusercontent.com/5360142/127743341-f83739f6-ebc3-4df5-93ff-5b880f55f009.png">

**Comment by porres** [comment]
@Lucarda, you gotta tell us what is the magic that you do and @emviveros needs to learn how to do it for the raspberry pi versions so he can get us a single package with the arm versions ;)

**Comment by emviveros** [comment]
I tested here again in Ubuntu 12.04LTS and cyclone 0.5-6 Lowercase and Uppercase fail.
![Captura de Tela 2021-07-31 às 12 00 12](https://user-images.githubusercontent.com/3089536/127743968-d5c20218-3d1e-4117-8007-01108222170e.png)    
![Captura de Tela 2021-07-31 às 12 01 19](https://user-images.githubusercontent.com/3089536/127744011-25cd56c8-95f7-4f0c-9f81-8508623896e5.png)

**Comment by porres** [comment]
I screwed up. I can't upload to deken from my mac machine, it screws it up.

Try Lucarda's link Esteban. And maybe one of you can upload this new package to deken

**Comment by emviveros** [comment]
I tried new selfcompiled version from current master repository and now all works like a charm..

I compiled usind pdlibbuilder:
```make PDINCLUDEDIR='/home/pi/src/pd-0.51-4_compilado/src' && make install PDLIBDIR=../```

And no problems with upper and lowercase in Ubuntu 12.04 and cyclone in current master branch

**Comment by emviveros** [comment]
> Here are Linux binaries in a single pkg:
> 
> [cyclone_0.5-6_Linux-i386-amd64.zip](https://github.com/porres/pd-cyclone/files/6910808/cyclone_0.5-6_Linux-i386-amd64.zip)

@Lucarda, I tested it here in Ubuntu 12.04 and it worked as expected. Uppercase and Lowercase objects name run like you described and we have the symlinks correctly in the cyclone externals directory.

You can test my compilation there to know if we can continue using ubuntu 12.04 to compile the externals as we already doing?
[cycloneCompiladoEsteban.zip](https://github.com/porres/pd-cyclone/files/6911442/cycloneCompiladoEsteban.zip)

**Comment by Lucarda** [comment]
@emviveros 

> You can test my compilation there to know if we can continue using ubuntu 12.04 to compile the externals as we already doing?

It worked ok on my computer.


@porres 

>  you gotta tell us what is the magic that you do and @emviveros needs to learn how to do it for the raspberry pi versions so he can get us a single package with the arm versions ;)

I add the extension accordingly alla:

`make install extension=l_amd64` 

Then I copy all in a single folder (over-writing the datadir files).

Here is the list of extensions:

|Operating System|	CPU-architecture|	filename|
|:-------------  |  :---------------  |-------------:|
|Linux	|unspecified (any architecture)	|.pd_linux|
|Linux	|i386 (Intel/AMD 32bit)	|.l_i386|
|Linux	|amd64 (Intel/AMD 64bit)	|.l_amd64|
|Linux	|arm (e.g. RaspberryPi)	|.l_arm|
|Linux	|arm64	|.l_arm64|

**Comment by porres** [comment]
well, so both of you nailed it I guess. Who can upload the linux packages to deken?

I think @Lucarda is well acquainted in uploading things to deken, right? :) 

@emviveros , can you give us a package for the raspberry pis so lucarda can upload them?

**Comment by porres** [comment]
@Lucarda, you're also an expert in building for windows, can you do that too?

**Comment by mxa** [comment]
@clwe is affected by this.

**Comment by porres** [comment]
> I'm stopping the show as I came to #555

seems we seem to have fixed this with https://github.com/porres/pd-cyclone/commit/cff79f68ddcdf53d43939582eff4cc8b5fe5fccc

here we go again! => https://github.com/porres/pd-cyclone/releases/tag/cyclone_0.5-6

**Comment by porres** [comment]
> done => https://github.com/porres/pd-cyclone/releases/tag/cyclone_0.5-6

had to update it, let's do it now!

**Comment by Lucarda** [comment]
This was not tested before but I'm having issues on linux-i386 builds.

I can create [cyclone/Bucket] but i can not create [cyclone/Clip] I get a crash on linux-i386 (does work on linux-amd64).

?

**Comment by porres** [comment]
> I can create [cyclone/Bucket] but i can not create [cyclone/Clip] I get a crash on linux-i386 (does work on linux-amd64).

what else can you create? Only [cyclone/Clip] is the issue?

**Comment by porres** [comment]
And what about 'nilwind'? Can you create and use them all?

**Comment by Lucarda** [comment]
> what else can you create? Is the issue really just with [cyclone/Clip] only?

On linux-i386:


|object|loads?|
|:----|-----:|
|cyclone/Append |crash|
|cyclone/Borax |yes *|
|cyclone/Bucket |yes|
|cyclone/Clip |crash|
|cyclone/Decode |yes|
|cyclone/Histo |yes|
|cyclone/MouseState |yes|
|cyclone/Peak |crash|
|cyclone/Table |yes|
|cyclone/TogEdge |yes|
|cyclone/Trough |crash|
|cyclone/Uzi |crash|
|cyclone/Clip~ |crash|
|cyclone/Line~ |yes|
|cyclone/Scope~ |yes|
|cyclone/Snapshot~ |yes|


* no error telling to use [borax] instead

**Comment by Lucarda** [comment]
> And what about 'nilwind'? Can you create and use them all?

yes

**Comment by porres** [comment]
> no error telling to use [borax] instead

fixed with the last commit (https://github.com/porres/pd-cyclone/commit/06e93bc4f0fb3e0519114c173599b31db788b2a3) please test

**Comment by porres** [comment]
So we have 6 that are fucked up: Append / Clip / Clip~ / Peak / Trough / Uzi. Just to be sure, do they all work in linux-amd64?

**Comment by porres** [comment]
And just to also be 100% sure, all of these work with lower case letters, right?

**Comment by porres** [comment]
Well, since the actual issue here has been resolved without any code change, I'm closing this.

We can talk about the new issue here => https://github.com/porres/pd-cyclone/issues/556

**Comment by porres** [comment]
And please, let's move on. I still want to get the new release out as it is, see https://github.com/porres/pd-cyclone/releases/tag/cyclone_0.5-6

It corresponds to the last commit where I included the error for Borax

**Comment by porres** [comment]
@Lucarda, I'm hoping you can send me binaries for linux32/64 and windows 32/64, thanks!

**Comment by Lucarda** [comment]
Here are the binaries:

https://nc.nubegris.com.ar/index.php/s/RYb56qfmcM6wmHQ

Do not extract the Linux zip on a non-linux machine as it breaks the symlinks. (you can rename the zip file).

**Comment by porres** [comment]
> Do not extract the Linux zip on a non-linux machine as it breaks the symlinks

Oh yeah, can you upload these to deken? Forgot about that :)

**Comment by porres** [comment]
Oh, and the Windows binaries could also be packaged together, the 64 bit can have the m_amd64 extension, can you do that?

**Comment by Lucarda** [comment]
> Oh, and the Windows binaries could also be packaged together, the 64 bit can have the m_amd64 extension, can you do that?

No. This can be done but we need another build system (which will not work for cross-compiling. It needs IOhannes magic script).
Other option is statically link pthread.dll but that's not recommended. [coll] might have many instantiations and thats bad for static linking. 

BTW. I will upload to deken ASAP. Might be tomorrow.

**Comment by porres** [comment]
> BTW. I will upload to deken ASAP. Might be tomorrow.

forget about it, we're fixing #556 so I'll make yet a new release!

**Comment by porres** [comment]
HERE WE GO AGAIN!!!!! https://github.com/porres/pd-cyclone/releases/tag/cyclone_0.5-6

thanks a lot @Lucarda , you're the one!

**Comment by Lucarda** [comment]
I had uploaded these to Deken:

[cyclone_v0.5-6_Linux-amd64-32-Linux-i386-32.zip](https://github.com/porres/pd-cyclone/files/6940487/cyclone_v0.5-6_Linux-amd64-32-Linux-i386-32.zip)

[cyclone_v0.5-6_Windows-amd64-32.zip](https://github.com/porres/pd-cyclone/files/6940491/cyclone_v0.5-6_Windows-amd64-32.zip)

[cyclone_v0.5-6_Windows-i386-32.zip](https://github.com/porres/pd-cyclone/files/6940492/cyclone_v0.5-6_Windows-i386-32.zip)


let me know if removal is needed.

:)

**Comment by porres** [comment]
what do you mean? These correspond to https://github.com/porres/pd-cyclone/releases/tag/cyclone_0.5-6, right?

**Comment by porres** [comment]
> cyclone_v0.5-6_Linux-amd64-32-Linux-i386-32.zip

by downloading directly from the zip link you provided and deken, I'm seeing 'uzi' with a capital letter instead of lower case... and no symlinks

<img width="330" alt="Screen Shot 2021-08-05 at 14 45 08" src="https://user-images.githubusercontent.com/5360142/128396958-2c091c5f-9357-4c0b-b160-90e6913b0bf8.png">

**Comment by Lucarda** [comment]
When you extracted the zip on your mac did you get any warning about overwriting?

I get kind of the same errors on Windows but this is Ok.

Linux symlinks break on non-linux systems at extraction time.

This is the .dek file as shown in the xarchiver:

![Screenshot_2021-08-05_18-14-22](https://user-images.githubusercontent.com/25239522/128401232-bbf51092-50a0-4b2b-9fc3-953d2ac8abe9.png)

**Comment by Lucarda** [comment]
> what do you mean? These correspond to https://github.com/porres/pd-cyclone/releases/tag/cyclone_0.5-6, right?

Yes :)

**Comment by Lucarda** [comment]
I just checked installing via deken and its all good:

![Untitled](https://user-images.githubusercontent.com/25239522/128402821-19d6d6cb-4d72-4aec-a073-f9cfaf878446.png)

**Comment by Lucarda** [comment]
IIRC Windows and macOS are case-insensitive for filenames so there's an overwrite on extraction.
