### ISSUE TITLE
Append / Clip / Clip~ / Peak / Trough / Uzi crash in Linux32 with the 'cyclone/' prefix

### ISSUE THREAD

**Issue by porres** [porres/pd-cyclone#556]
see https://github.com/porres/pd-cyclone/issues/553#issuecomment-892490115

@lucarda, just to be sure, do they all work in linux-amd64? Is there a change in loading these without the cyclone/ prefix? Do they all load fine with lower case letters and the cyclone/prefix?

**Comment by porres** [comment]
Well, it's hard for me to tell why this would happen at all. We need a professional debugger here :/ otherwise I can't fix this.

**Comment by Lucarda** [comment]
> Is there a change in loading these without the cyclone/ prefix? 
 
 They work Ok without the prefix (adding cyclone to the search paths).
 
 > Do they all load fine with lower case letters and the cyclone/prefix?
 
 yes
 
 ----------------------
 i'm not sure if this helps: i tweaked
 
 `static void *clip_new(t_symbol *s, int ac, t_atom *av)`
 
 to 
 
 `static void *clip_new(int ac, t_atom *av)`
 
 this loads fine [cyclone/Clip] but crashes [cyclone/clip].

**Comment by porres** [comment]
> They work Ok without the prefix (adding cyclone to the search paths).

Wow, so they work just fine with capital letters but no cyclone/prefix? Sorry to always trying to be 100% sure! This needs an update on the subject.

**Comment by porres** [comment]
one way or another, nothing makes sense anyway

**Comment by porres** [comment]
> i'm not sure if this helps

I'm pretty sure 't_symbol *s' is needed... and I can't see why this makes it work...

**Comment by porres** [comment]
When you're testing, are you using binaries for both 32 and 64 bits in the same folder?

**Comment by porres** [comment]
https://github.com/porres/pd-cyclone/commit/7f64e7c075f177ee0d7ce0a906bab342bb4b9c85 should close this

can you test it @Lucarda?

**Comment by porres** [comment]
actually, this should work too... https://github.com/porres/pd-cyclone/commit/7c9f71f7e10ec1ab9b1b75dfe98939f32781c641

could you test both? 

thanks!

**Comment by Lucarda** [comment]
All tests passing good.

Win32-64 / Linux32-64:

Objects created with/without slash declaration with uppercase and lowercase.

May be one more commit before release. You can make more consistent errors without the "cyclone/" in objects:


````
Cyclone: please use [append] instead of [Append] to supress this error
Cyclone: please use [borax] instead of [Borax] to supress this error
Cyclone: please use [bucket] instead of [Bucket] to supress this error
Cyclone: please use [cyclone/clip] instead of [Clip] to supress this error
Cyclone: please use [decode] instead of [Decode] to supress this error
Cyclone: please use [histo] instead of [Histo] to supress this error
Cyclone: please use [mousestate] instead of [MouseState] to supress this error
Cyclone: please use [peak] instead of [Peak] to supress this error
Cyclone: please use [cyclone/table] instead of [Table] to supress this error
Cyclone: please use [togedge] instead of [TogEdge] to supress this error
Cyclone: please use [trough] instead of [Trough] to supress this error
Cyclone: please use [uzi] instead of [Uzi] to supress this error
Cyclone: please use [cyclone/clip] instead of [Clip] to supress this error
Cyclone: please use [cyclone/line] instead of [Line] to supress this error
Cyclone: please use [scope] instead of [Scope] to supress this error
Cyclone: please use [cyclone/snapshot] instead of [Snapshot] to supress this error
````

**Comment by porres** [comment]
what's inconsistent?

**Comment by porres** [comment]
some objects need 'cyclone/', maybe that's the iconsistency, but that's it... anyway, thanks!
