### ISSUE TITLE
[play~ $1] fails therefore it's harder to create an abstraction with play~

### ISSUE THREAD

**Issue by jamshark70** [porres/pd-cyclone#569]
I was just trying to create an abstraction wrapping play~.

Of course it shouldn't assume a hardcoded table name. So I wrote [play~ $1].

"couldn't create"

I find https://github.com/porres/pd-cyclone/issues/191 -- the logic here appears to be, "If we can't be 100% certain that play~'s first argument is a symbol, then fail."

I'd submit that it would be more useful to recast this logic as "If we *are* certain that the first argument is *not* a symbol, then fail." When the argument is $1, users might actually know what they are doing and provide a symbol... so why should this be disallowed?

Sure, I can work around this using "args 0" --> pdcontrol. But... why make it harder than it needs to be?

**Comment by porres** [comment]
it turns out [play~ 1] doesn't fail creation in MAX, so...

**Comment by jamshark70** [comment]
OK, thanks :grin:
