### ISSUE TITLE
Installing Cyclone on mac

### ISSUE THREAD

**Issue by 0ort9** [porres/pd-cyclone#584]
Heyhey, i just switched from a windows pc to a macbook and having some trouble installing cyclone. It does not show up for me in dekken. I thried to install it from downloading the latest release from here and linked pure data to my external folder and included the lib/path declare object. My patches are still not working. Other libraries do not show the problem. Can anyone walk me through the process of installing a library manually on a mac? Would be appreciated!

**Comment by chunthebear** [comment]
Same problem! macOS Monterey, 12.3, M1 Pro.

**Comment by porres** [comment]
cyclone doesn't work on M1 natively (yet), you need to run it on roseta mode. I'm closing this in favor of https://github.com/porres/pd-cyclone/issues/586

next release should include native binaries
