### ISSUE TITLE
number/number~

### ISSUE THREAD

**Issue by porres** [porres/pd-cyclone#591]
**number~**
- Left outlet outputs nothing in input mode, that's not how it works in MAX
- In properties, 'height' should be renamed to 'Font Size'
- revise attributes

**number**
- add help file
- remove 'label'
- should also deal in the same way with heigth/font size and have just a single parameter.
- Why is lower and maximum not "infinite"? I guess we can make this like gatom and have 0/0 be unlimited
- we should apply some fixes for [number] that I have already proposed for vanilla, like not setting to '0' after you hit enter.

**both**
- default colors as in MAX 7+

**Comment by timothyschoen** [comment]
Ah I understand now how it works in Max, I'll take a look at that soon. Same colours as Max is possible, I'll use the label colour property for text colour, and the foreground colour property for the icon. This is possible because we'll get rid of the labels anyway. 

Agree with all this, I'd like to add that the arrow keys on the number should be implemented to increment/decrement the value as well.

**Comment by porres** [comment]
> Agree with all this, I'd like to add that the arrow keys on the number should be implemented to increment/decrement the value as well.

I wanted to add that to vanilla's gatom number box, we could open a request

**Comment by timothyschoen** [comment]
Great idea, should be a very small change as well.

**Comment by timothyschoen** [comment]
The problem is in Pd's core, it doesn't pass arrow keys to objects at all. The only way to solve it would be by creating a pull request for Pd. I really think it should pass on arrow keys anyway, as long as we're not in edit mode.

**Comment by porres** [comment]
> open an issue on Pd maybe?

I'll open a feature request

**Comment by porres** [comment]
just did it, it's 1709, chek it out https://github.com/pure-data/pure-data/issues

**Comment by porres** [comment]
Hey, I upgraded [comment] and improved/fixed many things!!! I would love now that its properties windows would also allow us to pick background and text colors. I have this on my to do list before upgrading the library to version 0.7 including also the number/number~ objects.

**Comment by timothyschoen** [comment]
I'm still putting the finishing touches on number/number~, I'll look at it after that!

**Comment by timothyschoen** [comment]
The problem with Max colours is that the inlets/outlets are hardly visible...

**Comment by porres** [comment]
> The problem with Max colours is that the inlets/outlets are hardly visible...

hmmm, just realized they aren't visible at all in my abstraction, hahahahah

well, honestly, I don't care about the color theme...

**Comment by timothyschoen** [comment]
Me neither, and I'd honestly prefer it if they look like native Pd objects. Copying the functionality of Max is more important.

**Comment by porres** [comment]
well, truth is I don't care about cyclone anymore :)

**Comment by timothyschoen** [comment]
hehe I know, thanks for working through these objects with me anyway!

**Comment by porres** [comment]
it's a dirty job but someone's gotta do it... I'm being also selfish anyway, I "stole" comment into ELSE with "note" (I guess it's not stealing when you work on it for years...), and an object like [nbx~] would also be cool. I need help getting through with tcl/tk though, get a grip on how to code decent properties windows... other objects in ELSE need that, like [function]/[messbox] and stuff.

**Comment by timothyschoen** [comment]
Steal whatever you want, that's why it's open-source!

I'd recommend using the number~ object as a base for ELSE's nbx~, and then detect whether there's a signal connected or not. You could even keep the icon, but have it change automatically, just to make that behaviour a bit more transparent.

I've learned how to do these property boxes over the last days by modifying the IEMGUI boxes. It's really a pain in the ass, I have no idea what I'm doing most of the time. You also have to repeat yourself a lot just to get basic stuff done... Generally I find it easier to take something that works and remove everything I don't want, than to write something from scratch.

**Comment by porres** [comment]
> I'm still putting the finishing touches on number/number~

Is this coming this soon?

**Comment by timothyschoen** [comment]
Hopefully! I've implemented all your suggestions, I'm now testing and working on the helpfiles.

**Comment by porres** [comment]
I can do help files, just give me a draft one

**Comment by timothyschoen** [comment]
https://user-images.githubusercontent.com/44585538/181995882-98f77d94-c292-40df-a088-b812890cb0ef.mov

Max documentation says that set shouldn't cause output but... oops. My number~ doesn't output the value on "set", but it also doesn't show the value until it has received a bang. Unfortunately it's not so easy to fix that. It's only a small detail.

**Comment by porres** [comment]
> Max documentation says that set shouldn't cause output but... oops.

Welcome to Cyclone, where you not only realize how the design of MAX object is ridiculous, but you also realize that their glorious and highly praised as so much superior than Pd's documentation is usually just fucking wrong!

**Comment by porres** [comment]
> Unfortunately it's not so easy to fix that. It's only a small detail.

why is it so hard? Just send what you have, let's have a look

**Comment by timothyschoen** [comment]
I've managed to get keys working on number, I'll take a look at the number~ issue now. 

The problem is that there will be two different states for the output value, so I'll have to make sure I pick the right one everywhere, and also apply min/max limits to both values. Just kinda annoying, but I'll get through it.

**Comment by porres** [comment]
Ok, so, more things.

number~ in MAX doesn't seem to allow color changes in to the state icon, which seems fucked up and stupid as usual... 

number has 4 color settings, you can set triangle color when it is not activated and when it is activated (we currently have only 3).

number can also show hexadecimal values, which, hey, it's cool! Actually, it can do much more. Formar values:
   0 = 'Decimal (Integer)' 
   1 = 'Hex' 
   2 = 'Roland Octal' 
   3 = 'Binary' 
   4 = 'MIDI' 
   5 = 'MIDI (C4)' 
   6 = 'Decimal (Floating-Point)'

And, well, hey, it's right there, it also has a floating point format????

Actually, it's got lots and lots of things... and, hey, you know what? Maybe I can steal this thing for ELSE after all... ;) and have my own super number box that also has a 'float' and we don't have to deal with the nightmare that it is to try and mimick MAX's design choices!

**Comment by porres** [comment]
> nightmare that it is to try and mimick MAX's design choices

well, for GUIs, the whole thing is just quite impossible, since we cannot do all things that MAX's GUI can usually... we don't have a transparency factor for instance... 

Cyclone currently only has two compiled GUI objects and I did include the number~ abstraction, the comment object was almost deleted but I kept on going and I am still struggling with it a lot. I ended up liking the idea of having a more powerful comment, but it will never be able to mimick the current power of MAX's comment object...

The idea of actually working on a number~ object is weird as we won't be able to make it really look like that...

Sorry I don't know what to do yet, worst case scenario I will put these two objects into ELSE.
