### ISSUE TITLE
counter_setup not found when loading patches in PDParty

### ISSUE THREAD

**Issue by lo94** [porres/pd-cyclone#597]
Greetings!  I was trying out Cyclone on PDParty (I downloaded the beta version) and I was attempting to use the counter object, however when doing so I receive a "counter_setup" not found error.  I am unsure if Cyclone worked with the old version of PDParty, but I figured I'd start here

**Comment by porres** [comment]
> I am unsure if Cyclone worked with the old version of PDParty, but I figured I'd start here

dunno either, don't know if any old version of cyclone/pdparty worked together, if other objects from cyclone work there, how it is supposed to work or be compiled, etc... 

afraid I cant help, I don't see anything particular weird to counter

**Comment by porres** [comment]
https://github.com/lo94 have you figured something out?

**Comment by porres** [comment]
@lo94 have you figured something out?

**Comment by porres** [comment]
I have to close this as we need feedback to keep this active, please reopen if you have more information
