### ISSUE TITLE
zl iter seems not work through all list with big lists

### ISSUE THREAD

**Issue by charlesneimog** [porres/pd-cyclone#614]
Hi, 
See this patch (I am on Linux),

[iter-bug.zip](https://github.com/porres/pd-cyclone/files/10774870/iter-bug.zip)

I am working with big lists (migrating from OM), and `zl iter 2` not iterate through all the big list, it stops before. In lists like `1 2 3 4 5 6 7 8 9 10` this do not happen.

There is an similar object in else?

Thanks!

**Comment by porres** [comment]
> There is an similar object in else?

[iterate], which is an abstraction, so it may work (if not, we have to open an issue for [list store])

**Comment by porres** [comment]
oh, [zl iter 2] is different, and it is the same as [zl group 2]

else [iterate] is just for 1 element... 

cyclone max has this stupid design where functions overlap in functionality...


trying with [else/group 2] works.

**Comment by charlesneimog** [comment]
great thanks, else/group 2 works!

**Comment by porres** [comment]
zl is also stupid that it has a default max size of 256, you need to use an attribute to increase this as your list is 438 long

[zl iter 2 @zlmaxsize 512] or [zl group 2 @zlmaxsize 512]

should work

but this is why I think ELSE is much better designed :) much easier to use options

**Comment by charlesneimog** [comment]
Ahhh, it is true, I forgot it... Thanks again!!!
