### ISSUE TITLE
play~ right outlet

### ISSUE THREAD

**Issue by jamshark70** [porres/pd-cyclone#615]
[play~]'s right outlet appears to be sending a bang once for every *sample* in the control block when it stopped. Expected behavior would be to bang *once* only when stopping.

![pd-play-multiple-bangs](https://user-images.githubusercontent.com/318301/220056941-c80f1824-e6ca-47d8-a395-5d94a8ad8c0e.png)

[23-0220-play-extra-bangs-rename-to-pd.txt](https://github.com/porres/pd-cyclone/files/10782294/23-0220-play-extra-bangs-rename-to-pd.txt)

*One* click of the start message produces, 1 second later:

```
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
right-outlet: bang
```

In the context where I found it, this was triggering messages into a cold inlet so it was no big deal, but it doesn't quite look like deliberate behavior.

**Comment by porres** [comment]
sorry this missed today's release, hopefully another update is coming soon

I will try to fix the same and update this week else/tabplayer~ object which is based on this

**Comment by jamshark70** [comment]
Thanks! That's fast :+1:
