### ISSUE TITLE
[comment] issue in Cyclone 0.7-0 / Linux Mint 21

### ISSUE THREAD

**Issue by joe-rouen** [porres/pd-cyclone#620]
1- Thank you for releasing Cyclone v.0.7.-0.

2- I have an issue under Linux Mint 21 (Ubuntu 22.04 base) with the latest Cyclone installed through Pd 0.53-2 / Deken.
After adding [comment] to an existing patch I can't moved it (in Edit mode both zoom-out / zoom-in).
I'm getting the following error messages in the Pd console:
```
comment: no method for '_motion'
comment: no method for '_release'
```
But I can still move all the other objects in my patch.

3- Deleting then adding a new [comment] to my same patch it seems to be working for the time being.
But it needs further tests from my side.

4- I'm also having troubles with [else/note] (v.1.0-0 rc-6) of which the behavior is unstable and unpredictable.
This is why I returned to Pd's Menu/Add/Comment, even if it's much less flexible and sexy.

**Comment by porres** [comment]
this is known, it happens to me at random so the problem is how to reproduce this and investigate the fix.

**Comment by porres** [comment]
> this is known

https://github.com/porres/pd-cyclone/issues/436#issuecomment-1107605747

**Comment by joe-rouen** [comment]
1- Well, let's see...

2- After further testing [comment], I put it in the GOP part of my SMS Vanilla patch, and there it's even worse.
Closing my patch for returning to its GOP, its full content completely disappeared (totally blank).

And I'm getting in Pd console the following error:
```
(Tcl) COMMANDE INVALIDE : invalid command name ".x55f4ce0cd5a0.c"
    while executing
".x55f4ce0cd5a0.c delete all55f4ce3dbc30"
    ("uplevel" body line 5)
    invoked from within
"uplevel #0 $docmds"
```

3- I already had similar issues with [else/note] as well as this object not being positioned at its original place when displaying only the GOP.

**Comment by porres** [comment]
please send a patch I can test and steps to reproduce

**Comment by joe-rouen** [comment]
I tried to drill down my issue as far as I could.

It seems there are interactions in cascade between GUI objects.
For me even if [cyclone/comment] and [else/note] have some random behaviors, there is a basic feature in Pure Data Vanilla which is also impacting the behavior of all GUI objects: i.e. the "GOP".
This should be fixed by the appropriate developers before trying to spend more time on your 2 objects.

I tried to be as simple as possible and built from scratch some very basic GOP patches.
GOP behavior is unstable and unpredictable not giving all the time the same results from one patch to an other one. See the here-attached patches and screen capture in the ZIP file.

There is at least 2 behaviors of GOP:
1- Good behavior: you can change the size or maximize its window - without GOP is moving inside.
2- Bad behavior: when changing the size or maximizing its window - GOP is moving inside. But this is not applying, as far as I know, to the parent patch containing the GOP.
This is the case with my SMS Vanilla project.

[PD-GOP_Testing.zip](https://github.com/porres/pd-cyclone/files/10817125/PD-GOP_Testing.zip)

**Comment by porres** [comment]
> there is a basic feature in Pure Data Vanilla which is also impacting the behavior of all GUI objects: i.e. the "GOP".
> This should be fixed by the appropriate developers before trying to spend more time on your 2 objects.

what do you mean? why don't you open an issue on vanilla's github?

**Comment by porres** [comment]
> [PD-GOP_Testing.zip](https://github.com/porres/pd-cyclone/files/10817125/PD-GOP_Testing.zip)

this is meaningless to me and I can't see any issues

**Comment by joe-rouen** [comment]
In such a case just forget it.
