### ISSUE TITLE
cyclone 0.7-0 not compiled

### ISSUE THREAD

**Issue by runout88** [porres/pd-cyclone#624]
Both the readme in the source code package and the blurb on the main page mentions that compiled binaries can be downloaded from https://github.com/porres/pd-cyclone/releases
Besides the issue that you don't deliver what you promise, a more serious consideration is for those who are using PD on a computer that is not connected to the internet so they can't use the "Help => Find Externals" you mention.
Please remedy the situation as soon as possible as this has been going on for almost six weeks.
Thank you in advance.

**Comment by umlaeute** [comment]
did you know that you can use https://deken.puredata.info/ as a web-frontend to the built-in package manager?
it allows you to download the package files, transfer them via sneakernet to your offline computer and install them from the  <kbd>Help</kbd>-><kbd>Find Externals</kbd>. (and no, I don't think this needs to be documented specifically for cyclone)

**Comment by porres** [comment]
my actual plan now is to use github actions like I'm doing with else so people can download builds for all commits

**Comment by porres** [comment]
closing in favor of https://github.com/porres/pd-cyclone/issues/629

anyway, for the next release I'll also make sure to add the binaries

**Comment by porres** [comment]
and 7.0.1 is coming out soon by the way, right after I finish the huge ELSE update
