### ISSUE TITLE
README.pdf is outdated

### ISSUE THREAD

**Issue by umlaeute** [porres/pd-cyclone#626]
the [README.pdf](https://github.com/porres/pd-cyclone/blob/ef21c349830dc80c13e90e71f28701c7b9198db6/README.pdf) appears to be just generated from the [README.md](https://github.com/porres/pd-cyclone/blob/ef21c349830dc80c13e90e71f28701c7b9198db6/README.md) so in the strict "source code" sense, there's no need to track both files: the markdown file would be sufficient. you could generate the pdf during build (if you want to include it in the deken packages) or in some separate github action (if you want it to appear as a web resource).

in any case, what's more worrying is that the `README.pdf` is currently outdated.

| commit | source | displayed version |
|---|---|---|
| [master](https://github.com/porres/pd-cyclone/tree/48dd011ac904c61b688251f5d513cdebe53eb8be) | [README.md](https://github.com/porres/pd-cyclone/blob/48dd011ac904c61b688251f5d513cdebe53eb8be/README.md) | 0.7-1 |
| [master](https://github.com/porres/pd-cyclone/tree/48dd011ac904c61b688251f5d513cdebe53eb8be) | [README.pdf](https://github.com/porres/pd-cyclone/blob/48dd011ac904c61b688251f5d513cdebe53eb8be/README.pdf) | 0.6-1 |
| [cyclone_0.7-0](https://github.com/porres/pd-cyclone/tree/cyclone_0.7-0) | [README.md](https://github.com/porres/pd-cyclone/blob/cyclone_0.7-0/README.md) |  0.7 |
| [cyclone_0.7-0](https://github.com/porres/pd-cyclone/tree/cyclone_0.7-0) | [README.pdf](https://github.com/porres/pd-cyclone/blob/ef21c349830dc80c13e90e71f28701c7b9198db6/README.pdf) | **0.6-1**

(I see you've updated the `README.md` a couple of hours ago, and left out the `README.pdf`; that's *probably* intentional (I personally wouldn't want to update generated files whenever i change the sources - that's a task for the computer; but then, I try to avoid tracking any generated files in the first place :wink: ). However I'm pretty sure that the **0.6-1** README.pdf in the *Cyclone 0.7-0* release is unintentional.)

**Comment by porres** [comment]
yeah, when working on the readme I realized I shipped it wrong last time :( will try to make an update soon to fix this

**Comment by umlaeute** [comment]
i would prefer it if the README.pdf was removed entirely from the repository, so it's obvious which one holds the correct information. (and build the pdf in a github action)

**Comment by porres** [comment]
closing in favor of https://github.com/porres/pd-cyclone/issues/629
