### ISSUE TITLE
useless include of 's_utf8.h'

### ISSUE THREAD

**Issue by umlaeute** [porres/pd-cyclone#627]
https://github.com/porres/pd-cyclone/blob/48dd011ac904c61b688251f5d513cdebe53eb8be/cyclone_objects/binaries/control/comment.c#L20-L22

this appears to be unnecessary, as no symbols from `s_utf8.h` are used anywhere.

since the header file has been removed from Pd-0.54, please remove those lines as well..

**Comment by porres** [comment]
this is the same case as else/note, which comment is now based on, so it has the same issues for cleaning it up I know

**Comment by umlaeute** [comment]
well yeah. but `else/note` does use a symbol from `s_utf8.h` (namely `utf8_dec()`, iirc), whereas `cyclone/comment` does not.

so there is no use to keeping the include here.

**Comment by umlaeute** [comment]
:facepalm:, me is searching for the wrong terms.

**Comment by porres** [comment]
closing in favor of https://github.com/porres/pd-cyclone/issues/628
