### ISSUE TITLE
add github actions

### ISSUE THREAD

**Issue by porres** [porres/pd-cyclone#629]
before a next release I'd like to have a github actions, would you be able to help with this as well @charlesneimog ?

Thanks

**Comment by porres** [comment]
Also check about creating the pdf with actions, see https://github.com/porres/pd-cyclone/issues/626

**Comment by charlesneimog** [comment]
Hi, actions are working for Windows and Linux, but there is an error related to #628 on Mac (`include not found`). How do you solve it?

**Comment by charlesneimog** [comment]
Ficou pior, agora nenhum acha esse `#include "s_cycloneutf8.h"`. Antes era so nos macs.....

**Comment by porres** [comment]
Ahahahha claro, enfim, um momento

**Comment by charlesneimog** [comment]
aahah, ainda não....

```
cyclone_objects/binaries/control/comment.c:20:10: fatal error: common/s_cycloneutf8.h: No such file or directory
   20 | #include "common/s_cycloneutf8.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

```

**Comment by porres** [comment]
agora foi
