### ISSUE TITLE
pd quits when trying to open any cyclone helpfile

### ISSUE THREAD

**Issue by shx-vhs** [porres/pd-cyclone#631]
Any suggestions? I am using pd 0.54-0 on macOS Catalina 10.15.7
Thanks!

**Comment by porres** [comment]
this seems to have been fixed in the current master

**Comment by shx-vhs** [comment]
Solved

**Comment by porres** [comment]
Can you open help file with f comment?

**Comment by shx-vhs** [comment]
What exactly do you mean? Opening the help file for the comment object? Yes this works.
