### ISSUE TITLE
zl group arg is not initialized (is = 0)

### ISSUE THREAD

**Issue by jamshark70** [porres/pd-cyclone#639]
The following patch in Max prints `print: 49 57 51 52`

![zlgroup-max](https://github.com/porres/pd-cyclone/assets/318301/1951d80d-fea3-4ac3-b5af-48be5db337de)

The following patch in Pd produces no output at all.

![zlgroup-pd](https://github.com/porres/pd-cyclone/assets/318301/befae08c-9825-4e64-b00f-89d938f857e1)

Therefore, there is an incompatibility: cyclone/zl in "group" mode does not respond to "bang" in the same way that the Max object does.

I can work around it -- just that it would have been more convincing for this class demo to say that [zl group] in Pd behaves the same as in Max.

**Comment by porres** [comment]
the bang message works, the bug is that the group size is not initialized somehow
