### ISSUE TITLE
FTBFS with gcc-14

### ISSUE THREAD

**Issue by umlaeute** [porres/pd-cyclone#645]
see https://bugs.debian.org/1075369

**Comment by porres** [comment]
hopefully fixed by https://github.com/porres/pd-cyclone/commit/22f40dafcecb0deca8d38f17bec1d10654ce6f35

please confirm

**Comment by porres** [comment]
I think this also fixes https://github.com/porres/pd-cyclone/commit/694caf4a5dd164f1f8711b7de96a58f4992a8e0b please confirm

**Comment by umlaeute** [comment]
1. the problems with bitand/bitor/bitxor are fixed
2. the problem with cybuf has **not** been fixed (or rather: fixed wrongly). the correct fix would be to use `t_word** vectors` (also note the cast in the `getbytes` cast)

**Comment by porres** [comment]
please confirm that https://github.com/porres/pd-cyclone/commit/2b2464a45400f72aa5db28fbd1dbe7bf57a2e68e actually solves this

**Comment by umlaeute** [comment]
i can confirm that the build now succeeds.

you probably should still remove the cast in https://github.com/porres/pd-cyclone/blob/2b2464a45400f72aa5db28fbd1dbe7bf57a2e68e/shared/signal/cybuf.c#L290

```diff
diff --git a/shared/signal/cybuf.c b/shared/signal/cybuf.c
index e5769d8b..0d993e17 100644
--- a/shared/signal/cybuf.c
+++ b/shared/signal/cybuf.c
@@ -287,7 +287,7 @@ void *cybuf_init(t_class *owner, t_symbol *bufname, int numchans, int singlemode
     c->c_single = singlemode;
     c->c_owner = owner;
     c->c_npts = 0;
-    c->c_vectors = (t_word**)vectors;
+    c->c_vectors = vectors;
     c->c_channames = channames;
     c->c_disabled = 0;
     c->c_playable = 0;
```


a pointer cast will of course shut up any compiler-warnings, but it is also a good way to shoot yourself in the knee (as the compiler is actually *warning* you of some inconsistencies).
in general it is better to fix the code that triggers a warning that just silence the warning.

(as of 2b2464a45400f72aa5db28fbd1dbe7bf57a2e68e, the type of `vectors` **is** `t_word**`, so everything is good. but if you ever change the type of `vectors` again (for whatever reasons), the cast in line 290 would prevent a warnings, which is bad)
