### ISSUE TITLE
clip fails to build for Pd64 

### ISSUE THREAD

**Issue by umlaeute** [porres/pd-cyclone#647]
you have https://github.com/porres/pd-cyclone/blob/694caf4a5dd164f1f8711b7de96a58f4992a8e0b/cyclone_objects/binaries/control/clip.c#L16-L17, but then you are using these in `floatinlet_new`: https://github.com/porres/pd-cyclone/blob/694caf4a5dd164f1f8711b7de96a58f4992a8e0b/cyclone_objects/binaries/control/clip.c#L132-L133

however, `floatinlet_new` really expects a `t_float*` argument (while you are giving it a `float*`).

**Comment by porres** [comment]
I hope that's all the bugs, hopefully may catch some more in the next few days if they exhist? I'll prepare an 0.9.1 update early next week...
